# Generated by scripts/generate-qc-actions.mjs. Do not edit by hand.
SHARED_QC_ACTIONS = {
  "reconnect_device": {
    "rpc": "device.reconnect",
    "classification": "risky-write",
    "access": "full",
    "description": "Reconnect the native Quad Cortex transport after explicit confirmation."
  },
  "reset_device_session": {
    "rpc": "device.resetSession",
    "classification": "risky-write",
    "access": "full",
    "description": "Reset and re-synchronize the native Quad Cortex communication session after explicit confirmation."
  },
  "disconnect_device": {
    "rpc": "device.disconnect",
    "classification": "risky-write",
    "access": "full",
    "description": "Close the native Quad Cortex transport after explicit confirmation."
  },
  "get_current_preset": {
    "rpc": "device.snapshot",
    "classification": "read",
    "access": "read-only",
    "description": "Read the authoritative current preset, scene, tempo and Grid state."
  },
  "get_state_events": {
    "rpc": "device.stateEvents",
    "classification": "read",
    "access": "read-only",
    "description": "Read native state frames after a sequence cursor."
  },
  "get_tempo_clock": {
    "rpc": "device.tempoClock",
    "classification": "read",
    "access": "read-only",
    "description": "Read the most recent native metronome beat, bar and tick state."
  },
  "get_block_details": {
    "rpc": "device.blockDetails",
    "classification": "read",
    "access": "read-only",
    "description": "Read live parameters for one occupied Grid block, splitter, or mixer."
  },
  "get_lane_control_details": {
    "rpc": "device.laneControlDetails",
    "classification": "read",
    "access": "read-only",
    "description": "Read the Input Gate or Lane Output parameters attached to a signal row."
  },
  "list_models": {
    "rpc": "device.listModels",
    "classification": "read",
    "access": "read-only",
    "description": "Find installed block models and their numeric IDs."
  },
  "list_presets": {
    "rpc": "device.listPresets",
    "classification": "read",
    "access": "read-only",
    "description": "List presets in a setlist, optionally refreshing the device index."
  },
  "list_preset_folders": {
    "rpc": "device.listPresetFolders",
    "classification": "read",
    "access": "read-only",
    "description": "List preset folders and setlists, optionally refreshing the device index."
  },
  "list_preset_slots": {
    "rpc": "device.listPresetSlots",
    "classification": "read",
    "access": "read-only",
    "description": "List preset destinations and their occupancy before a persistent write."
  },
  "get_master_volume": {
    "rpc": "device.masterVolume",
    "classification": "read",
    "access": "read-only",
    "description": "Read the authoritative master output volume."
  },
  "get_device_identity": {
    "rpc": "device.identity",
    "classification": "read",
    "access": "read-only",
    "description": "Read the connected Quad Cortex serial number, firmware version, type and custom name."
  },
  "get_inhibited_modules": {
    "rpc": "device.inhibitedModules",
    "classification": "read",
    "access": "read-only",
    "description": "Read the authoritative Global Gate and Global EQ inhibition state."
  },
  "get_tuner_settings": {
    "rpc": "device.tunerSettings",
    "classification": "read",
    "access": "read-only",
    "description": "Read the tuner input, mute preference, and reference pitch without changing or engaging the tuner."
  },
  "set_tuner_input": {
    "rpc": "device.setTunerInput",
    "classification": "risky-write",
    "access": "full",
    "description": "Choose the tuner input. This invisibly engages the tuner and can silence the rig if its mute preference is enabled."
  },
  "set_tuner_mute": {
    "rpc": "device.setTunerMute",
    "classification": "risky-write",
    "access": "full",
    "description": "Change mute-while-tuning. This invisibly engages the tuner; enabling mute immediately silences all outputs."
  },
  "restore_tuner_audio": {
    "rpc": "device.restoreTunerAudio",
    "classification": "risky-write",
    "access": "full",
    "description": "Restore audio after a host tuner write by clearing the persistent mute-while-tuning preference."
  },
  "set_tuner_reference": {
    "rpc": "device.setTunerReference",
    "classification": "risky-write",
    "access": "full",
    "description": "Set tuner reference as an Hz offset from 440. This invisibly engages the tuner."
  },
  "get_preset_screenshot": {
    "rpc": "device.presetScreenshot",
    "classification": "read",
    "access": "read-only",
    "description": "Read the PNG thumbnail stored for a preset."
  },
  "capture_screen": {
    "rpc": "device.captureScreen",
    "classification": "read",
    "access": "read-only",
    "description": "Capture the current Quad Cortex touchscreen as a PNG image."
  },
  "preview_parameter": {
    "rpc": "device.previewParameter",
    "classification": "live-write",
    "access": "modify",
    "description": "Preview a block, splitter, or mixer parameter value without waiting for device verification."
  },
  "preview_lane_control_parameter": {
    "rpc": "device.previewLaneControlParameter",
    "classification": "live-write",
    "access": "modify",
    "description": "Preview an Input Gate or Lane Output parameter without waiting for device verification."
  },
  "create_device_backup": {
    "rpc": "device.createBackup",
    "classification": "persistent-write",
    "access": "full",
    "description": "Create a complete local device backup after explicit confirmation."
  },
  "set_device_name": {
    "rpc": "device.setDeviceName",
    "classification": "persistent-write",
    "access": "full",
    "description": "Change the Quad Cortex custom name after explicit confirmation."
  },
  "undo_device": {
    "rpc": "device.undo",
    "classification": "risky-write",
    "access": "modify",
    "description": "Undo the most recent device edit after explicit confirmation."
  },
  "redo_device": {
    "rpc": "device.redo",
    "classification": "risky-write",
    "access": "modify",
    "description": "Redo the most recently undone device edit after explicit confirmation."
  },
  "tap_screen": {
    "rpc": "device.tapScreen",
    "classification": "risky-write",
    "access": "full",
    "description": "Tap an exact touchscreen pixel after reviewing a fresh screen capture and explicitly confirming the action."
  },
  "select_scene": {
    "rpc": "device.selectScene",
    "classification": "live-write",
    "access": "modify",
    "description": "Immediately select a performance scene, numbered 0 through 7."
  },
  "copy_scene": {
    "rpc": "device.copyScene",
    "classification": "live-write",
    "access": "modify",
    "description": "Copy or swap two scenes in the current preset and verify the resulting scene state."
  },
  "set_scene_label": {
    "rpc": "device.setSceneLabel",
    "classification": "live-write",
    "access": "modify",
    "description": "Set or clear the label of one scene in the current preset."
  },
  "set_scene_color": {
    "rpc": "device.setSceneColor",
    "classification": "live-write",
    "access": "modify",
    "description": "Set the display color of one scene in the current preset."
  },
  "press_footswitch": {
    "rpc": "device.pressFootswitch",
    "classification": "live-write",
    "access": "performance",
    "description": "Press a physical Quad Cortex footswitch by its stable hardware index."
  },
  "tap_tempo": {
    "rpc": "device.tapTempo",
    "classification": "live-write",
    "access": "performance",
    "description": "Tap the dedicated Quad Cortex tempo control through its official MIDI command."
  },
  "navigate_bank": {
    "rpc": "device.navigateBank",
    "classification": "live-write",
    "access": "performance",
    "description": "Immediately navigate one performance bank down (-1) or up (1)."
  },
  "show_tuner": {
    "rpc": "device.showTuner",
    "classification": "live-write",
    "access": "performance",
    "description": "Show or hide the tuner."
  },
  "show_gig_view": {
    "rpc": "device.showGigView",
    "classification": "live-write",
    "access": "performance",
    "description": "Show or hide Gig View."
  },
  "select_mode_slot": {
    "rpc": "device.selectModeSlot",
    "classification": "live-write",
    "access": "performance",
    "description": "Select device-configured performance Mode Slot A, B, or C."
  },
  "set_master_volume": {
    "rpc": "device.setMasterVolume",
    "classification": "risky-write",
    "access": "performance",
    "description": "Set master output volume after explicit user confirmation and stale-value validation."
  },
  "recall_preset": {
    "rpc": "device.recallPreset",
    "classification": "live-write",
    "access": "modify",
    "description": "Immediately recall a preset by setlist key and position."
  },
  "reload_preset": {
    "rpc": "device.reloadPreset",
    "classification": "risky-write",
    "access": "modify",
    "description": "Discard unsaved edits and reload the active preset after explicit host confirmation."
  },
  "set_tempo": {
    "rpc": "device.setTempo",
    "classification": "live-write",
    "access": "performance",
    "description": "Immediately set performance tempo from 40 through 240 BPM."
  },
  "set_bypass": {
    "rpc": "device.toggleBypass",
    "classification": "live-write",
    "access": "modify",
    "description": "Immediately enable or bypass one Grid block and verify device readback."
  },
  "set_parameter": {
    "rpc": "device.setParameter",
    "classification": "live-write",
    "access": "modify",
    "description": "Immediately set a writable block, splitter, or mixer parameter and verify it."
  },
  "set_parameter_scene_mode": {
    "rpc": "device.setParameterSceneMode",
    "classification": "live-write",
    "access": "modify",
    "description": "Enable or disable per-scene storage for a block, splitter, or mixer parameter and verify device readback."
  },
  "set_parameter_expression": {
    "rpc": "device.setParameterExpression",
    "classification": "live-write",
    "access": "modify",
    "description": "Assign EXP 1 or EXP 2 to a block, splitter, or mixer parameter, or clear it with pedal 0, preserving the requested heel and toe range."
  },
  "set_lane_control_parameter": {
    "rpc": "device.setLaneControlParameter",
    "classification": "live-write",
    "access": "modify",
    "description": "Set an Input Gate or Lane Output parameter with stale-value and preset guards."
  },
  "set_lane_control_scene_mode": {
    "rpc": "device.setLaneControlSceneMode",
    "classification": "live-write",
    "access": "modify",
    "description": "Enable or disable per-scene storage for an Input Gate or Lane Output parameter and verify readback."
  },
  "set_expression_bypass": {
    "rpc": "device.setExpressionBypass",
    "classification": "live-write",
    "access": "modify",
    "description": "Assign EXP 1 or EXP 2 to a block bypass with the QC switch mode, inversion, delay and latch-emulation settings."
  },
  "move_block": {
    "rpc": "device.moveBlock",
    "classification": "live-write",
    "access": "modify",
    "description": "Move an existing Grid block to an empty column in the same row with model and preset guards."
  },
  "add_block": {
    "rpc": "device.addBlock",
    "classification": "live-write",
    "access": "modify",
    "description": "Add an installed model to an empty Grid cell and verify the resulting block."
  },
  "remove_block": {
    "rpc": "device.removeBlock",
    "classification": "live-write",
    "access": "modify",
    "description": "Remove a Grid block after validating its model and active preset."
  },
  "set_block_footswitch": {
    "rpc": "device.setBlockFootswitch",
    "classification": "live-write",
    "access": "modify",
    "description": "Assign or clear a Grid block footswitch with preset, model and assignment guards."
  },
  "set_stomp_momentary": {
    "rpc": "device.setStompMomentary",
    "classification": "live-write",
    "access": "modify",
    "description": "Set a single-block STOMP footswitch to momentary or latching behavior and verify device readback."
  },
  "set_stomp_label": {
    "rpc": "device.setStompLabel",
    "classification": "live-write",
    "access": "modify",
    "description": "Set the visible label of a STOMP footswitch using the device's correct single- or multi-assignment storage."
  },
  "set_midi_out": {
    "rpc": "device.setMidiOut",
    "classification": "live-write",
    "access": "modify",
    "description": "Replace up to 12 MIDI Out messages for a footswitch or expression-pedal source in the current preset."
  },
  "set_preset_load_midi_out": {
    "rpc": "device.setPresetLoadMidiOut",
    "classification": "live-write",
    "access": "modify",
    "description": "Replace the MIDI Out messages sent when the current preset loads."
  },
  "set_chain_input": {
    "rpc": "device.setChainInput",
    "classification": "live-write",
    "access": "modify",
    "description": "Change a signal-row input after validating the current route and preset."
  },
  "set_chain_output": {
    "rpc": "device.setChainOutput",
    "classification": "live-write",
    "access": "modify",
    "description": "Change a signal-row output after validating the current route and preset."
  },
  "set_chain_split": {
    "rpc": "device.setChainSplit",
    "classification": "live-write",
    "access": "modify",
    "description": "Set or clear a signal-row split and rejoin with complete stale-route guards."
  },
  "set_split_mute": {
    "rpc": "device.setSplitMute",
    "classification": "live-write",
    "access": "modify",
    "description": "Mute or unmute a splitter/mixer path globally across scenes with exact device readback."
  },
  "save_preset_as": {
    "rpc": "device.savePresetAs",
    "classification": "persistent-write",
    "access": "modify",
    "description": "Save the current preset to a reviewed device slot with explicit overwrite confirmation."
  },
  "rename_current_preset": {
    "rpc": "device.renameCurrentPreset",
    "classification": "persistent-write",
    "access": "modify",
    "description": "Rename the active stored preset after explicit confirmation."
  },
  "copy_preset": {
    "rpc": "device.copyPreset",
    "classification": "persistent-write",
    "access": "modify",
    "description": "Copy a device preset to a reviewed destination with explicit overwrite confirmation."
  },
  "get_general_settings": {
    "rpc": "device.generalSettings",
    "classification": "read",
    "access": "read-only",
    "description": "Read the QC Device Settings and System settings without changing them."
  },
  "get_io_settings": {
    "rpc": "device.ioSettings",
    "classification": "read",
    "access": "read-only",
    "description": "Read complete input, output, headphone, USB, MIDI, expression-pedal, connection, and output-pairing settings."
  },
  "set_input_port": {
    "rpc": "device.setInputPort",
    "classification": "persistent-write",
    "access": "full",
    "description": "Change one or more settings for a QC input. Each supplied field is sent in its own hardware update; input gain is expressed safely in dB."
  },
  "set_output_port": {
    "rpc": "device.setOutputPort",
    "classification": "persistent-write",
    "access": "full",
    "description": "Change level, ground lift, or mute for one QC output. Every supplied field is sent in a separate hardware update."
  },
  "set_usb_port": {
    "rpc": "device.setUsbPort",
    "classification": "persistent-write",
    "access": "full",
    "description": "Change USB level, headphone source, or dry/wet routing using normalized device values and separate hardware updates."
  },
  "set_midi_thru": {
    "rpc": "device.setMidiThru",
    "classification": "persistent-write",
    "access": "full",
    "description": "Enable or disable the QC MIDI Thru setting after explicit confirmation."
  },
  "set_output_pairing": {
    "rpc": "device.setOutputPairing",
    "classification": "persistent-write",
    "access": "full",
    "description": "Pair or unpair output couples. Null leaves that output couple unchanged."
  },
  "get_global_eq": {
    "rpc": "device.globalEq",
    "classification": "read",
    "access": "read-only",
    "description": "Read Global EQ bypass state and all 28 normalized parameters."
  },
  "set_global_eq_bypassed": {
    "rpc": "device.setGlobalEqBypassed",
    "classification": "persistent-write",
    "access": "full",
    "description": "Enable or bypass the global EQ after explicit confirmation."
  },
  "set_global_eq_band": {
    "rpc": "device.setGlobalEqBand",
    "classification": "persistent-write",
    "access": "full",
    "description": "Update one Global EQ band with sparse normalized controls after explicit confirmation."
  },
  "set_global_eq_output": {
    "rpc": "device.setGlobalEqOutput",
    "classification": "persistent-write",
    "access": "full",
    "description": "Update Global EQ output level and output-pair assignments after explicit confirmation."
  },
  "get_mode_cycle": {
    "rpc": "device.modeCycle",
    "classification": "read",
    "access": "read-only",
    "description": "Read the configured footswitch modes in cycle order."
  },
  "set_mode_cycle": {
    "rpc": "device.setModeCycle",
    "classification": "persistent-write",
    "access": "full",
    "description": "Replace the ordered footswitch mode cycle after explicit confirmation."
  },
  "get_looper_status": {
    "rpc": "device.looperStatus",
    "classification": "read",
    "access": "read-only",
    "description": "Read the complete Looper X transport and progress state when a looper is present."
  },
  "control_looper": {
    "rpc": "device.controlLooper",
    "classification": "live-write",
    "access": "performance",
    "description": "Control Looper X through its documented MIDI CC interface."
  },
  "list_recents": {
    "rpc": "device.recents",
    "classification": "read",
    "access": "read-only",
    "description": "List recently used presets with authoritative folder metadata."
  },
  "list_favorites": {
    "rpc": "device.favorites",
    "classification": "read",
    "access": "read-only",
    "description": "List favorite presets using request correlation even when the reply omits its favorites flag."
  },
  "set_favorite": {
    "rpc": "device.setFavorite",
    "classification": "persistent-write",
    "access": "full",
    "description": "Add or remove one exact device library entry from Favorites after explicit confirmation."
  },
  "list_pinned_models": {
    "rpc": "device.pinnedModels",
    "classification": "read",
    "access": "read-only",
    "description": "List model IDs and capture keys pinned in the device model browser."
  },
  "set_model_pinned": {
    "rpc": "device.setModelPinned",
    "classification": "persistent-write",
    "access": "full",
    "description": "Pin or unpin one model ID after explicit confirmation."
  },
  "list_captures": {
    "rpc": "device.captures",
    "classification": "read",
    "access": "read-only",
    "description": "List loadable Neural Captures with their content keys and names."
  },
  "load_capture": {
    "rpc": "device.loadCapture",
    "classification": "live-write",
    "access": "modify",
    "description": "Place or retarget a Neural Capture block using a device library key and name."
  },
  "list_irs": {
    "rpc": "device.irs",
    "classification": "read",
    "access": "read-only",
    "description": "List loadable Impulse Responses from the whole library or a selected device folder."
  },
  "load_ir": {
    "rpc": "device.loadIr",
    "classification": "live-write",
    "access": "modify",
    "description": "Place or retarget an IR Loader and set one of its two IR slots by key and name."
  },
  "create_setlist": {
    "rpc": "device.createSetlist",
    "classification": "persistent-write",
    "access": "full",
    "description": "Create a user setlist after explicit confirmation."
  },
  "delete_setlist": {
    "rpc": "device.deleteSetlist",
    "classification": "persistent-write",
    "access": "full",
    "description": "Delete a named user setlist and its contents after explicit confirmation."
  },
  "duplicate_setlist": {
    "rpc": "device.duplicateSetlist",
    "classification": "persistent-write",
    "access": "full",
    "description": "Create a user setlist and copy its source presets through the shared recall-and-save workflow after explicit confirmation."
  },
  "delete_preset": {
    "rpc": "device.deletePreset",
    "classification": "persistent-write",
    "access": "full",
    "description": "Delete a named preset from a writable user setlist after explicit confirmation."
  },
  "move_preset": {
    "rpc": "device.movePreset",
    "classification": "persistent-write",
    "access": "full",
    "description": "Move a named preset to another slot in its user setlist after explicit confirmation."
  },
  "set_tempo_metronome": {
    "rpc": "device.setTempoMetronome",
    "classification": "persistent-write",
    "access": "full",
    "description": "Change named fields of the loaded preset's tempo/metronome block. Null leaves a field unchanged; time signature is applied before beat cells."
  },
  "set_tempo_mode": {
    "rpc": "device.setTempoMode",
    "classification": "persistent-write",
    "access": "full",
    "description": "Select whether the Quad Cortex uses the loaded preset tempo or its device-global tempo block."
  },
  "set_general_integer": {
    "rpc": "device.setGeneralInteger",
    "classification": "persistent-write",
    "access": "full",
    "description": "Change one validated integer Device Setting after explicit confirmation. Hold timing uses its wire index 0 through 5."
  },
  "set_general_toggle": {
    "rpc": "device.setGeneralToggle",
    "classification": "persistent-write",
    "access": "full",
    "description": "Change one validated on/off Device Setting after explicit confirmation."
  },
  "set_scene_bypass_behavior": {
    "rpc": "device.setSceneBypassBehavior",
    "classification": "persistent-write",
    "access": "full",
    "description": "Change the global scene block-bypass persistence behavior after explicit confirmation."
  },
  "set_master_volume_assignment": {
    "rpc": "device.setMasterVolumeAssignment",
    "classification": "persistent-write",
    "access": "full",
    "description": "Replace all four Master Volume output assignments atomically after explicit confirmation."
  },
  "set_global_bypass": {
    "rpc": "device.setGlobalBypass",
    "classification": "persistent-write",
    "access": "full",
    "description": "Replace all Cab and IR global-bypass row flags atomically after explicit confirmation."
  }
}
