// Generated by scripts/generate-qc-payloads.mjs. Do not edit by hand.

export interface GridBlock {
  id: string;
  modelId?: number;
  categoryId?: number;
  name: string;
  kind: "input" | "utility" | "capture" | "amp" | "cab" | "mod" | "delay" | "reverb" | "output";
  category?: string;
  plugin?: boolean;
  pluginId?: string;
  row: number;
  column: number;
  bypassed?: boolean;
  color?: string;
  glyph?: string;
  footswitch?: number;
  footswitchOrder?: number;
}

export interface FootswitchState {
  index: number;
  active: boolean;
  assigned: boolean;
  color: string;
  momentary?: boolean;
  label?: string;
}

export interface GridRoute {
  row: number;
  inputId?: number;
  outputId?: number;
  input: string;
  output: string;
  splitColumn?: number;
  mixColumn?: number;
}

export interface ModeSlot {
  slot: 0 | 1 | 2;
  label: string;
  mode: "PRESET" | "SCENE" | "STOMP" | "HYBRID";
}

export interface BypassUpdate {
  row: number;
  column: number;
  bypassed: boolean;
}

export interface QcStateUpdate {
  kind: "scene" | "dirty" | "master" | "sceneLabel" | "sceneColor" | "position" | "preset" | "bypass" | "bypassBatch" | "mode" | "tempo" | "parameter";
  activeScene?: number;
  dirty?: boolean;
  masterVolume?: number;
  index?: number;
  label?: string;
  color?: string;
  setlistKey?: string;
  position?: number;
  isFactory?: boolean;
  presetName?: string;
  tempo?: number;
  tempoLedEnabled?: boolean;
  scenes?: string[];
  sceneColors?: string[];
  blocks?: GridBlock[];
  routes?: GridRoute[];
  mode?: "PRESET" | "SCENE" | "STOMP" | "HYBRID";
  modeSlots?: ModeSlot[];
  footswitchModes?: ("PRESET" | "SCENE" | "STOMP")[];
  row?: number;
  column?: number;
  bypassed?: boolean;
  bypassUpdates?: BypassUpdate[];
  parameterIndex?: number;
  normalizedValue?: number;
  catalogRefresh?: boolean;
  observedAt?: number;
}

export interface ScalePoint {
  normalized: number;
  real: number;
}

export interface BlockParameter {
  index: number;
  displayPosition: number;
  name: string;
  normalizedValue: number | null;
  displayValue: string;
  units: string;
  type: string;
  minimum: number;
  maximum: number;
  valueScale: string;
  scaleExponent?: number | null;
  scalePoints: ScalePoint[];
  scaleKnown: boolean;
  displayPrecision?: number | null;
  minimumLabel?: string | null;
  midpointLabel?: string | null;
  maximumLabel?: string | null;
  steps?: number | null;
  sceneMode: boolean;
  options: string[];
  writable: boolean;
  enabled: boolean;
  expressionAssignable: boolean;
  linkedSceneMode?: number | null;
  expression?: number | null;
  expressionMinimum?: number | null;
  expressionMaximum?: number | null;
  ledValue?: number | null;
  wireValueKind: string;
}

export interface BlockDetails {
  row: number;
  column: number;
  modelId: number;
  name: string;
  category: string;
  scene: number;
  parameters: BlockParameter[];
}

export interface PresetSnapshot {
  deviceName: string;
  presetName: string;
  presetLocation: string;
  presetPosition: number;
  setlistKey: string;
  setlistName: string;
  mode: "PRESET" | "SCENE" | "STOMP" | "HYBRID";
  modeSlots?: ModeSlot[];
  footswitchModes?: ("PRESET" | "SCENE" | "STOMP")[];
  activeScene: number;
  scenes: string[];
  sceneColors?: string[];
  footswitchStates?: FootswitchState[];
  blocks: GridBlock[];
  routes: GridRoute[];
  tempo: number;
  tempoLedEnabled?: boolean;
  tempoPulseEpochMs?: number;
  masterVolume: number;
  dirty: boolean;
}

export interface DeviceActionResult {
  detail: string;
  snapshot?: PresetSnapshot;
}
