// Generated by scripts/generate-qc-actions.mjs. Do not edit by hand.
export const SHARED_QC_ACTIONS = [
  {
    "name": "reconnect_device",
    "rpc": "device.reconnect",
    "classification": "risky-write",
    "description": "Reconnect the native Quad Cortex transport after explicit confirmation.",
    "properties": {
      "confirm_risky_operation": "boolean"
    },
    "required": [
      "confirm_risky_operation"
    ],
    "access": "full",
    "inputSchema": {
      "type": "object",
      "properties": {
        "confirm_risky_operation": {
          "type": "boolean"
        }
      },
      "required": [
        "confirm_risky_operation"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "reset_device_session",
    "rpc": "device.resetSession",
    "classification": "risky-write",
    "description": "Reset and re-synchronize the native Quad Cortex communication session after explicit confirmation.",
    "properties": {
      "confirm_risky_operation": "boolean"
    },
    "required": [
      "confirm_risky_operation"
    ],
    "access": "full",
    "inputSchema": {
      "type": "object",
      "properties": {
        "confirm_risky_operation": {
          "type": "boolean"
        }
      },
      "required": [
        "confirm_risky_operation"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "disconnect_device",
    "rpc": "device.disconnect",
    "classification": "risky-write",
    "description": "Close the native Quad Cortex transport after explicit confirmation.",
    "properties": {
      "confirm_risky_operation": "boolean"
    },
    "required": [
      "confirm_risky_operation"
    ],
    "access": "full",
    "inputSchema": {
      "type": "object",
      "properties": {
        "confirm_risky_operation": {
          "type": "boolean"
        }
      },
      "required": [
        "confirm_risky_operation"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "get_current_preset",
    "rpc": "device.snapshot",
    "classification": "read",
    "description": "Read the authoritative current preset, scene, tempo and Grid state.",
    "properties": {},
    "required": [],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "get_state_events",
    "rpc": "device.stateEvents",
    "classification": "read",
    "description": "Read native state frames after a sequence cursor.",
    "properties": {
      "after_sequence": "integer",
      "limit": "integer"
    },
    "required": [
      "after_sequence",
      "limit"
    ],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {
        "after_sequence": {
          "type": "integer"
        },
        "limit": {
          "type": "integer"
        }
      },
      "required": [
        "after_sequence",
        "limit"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "get_tempo_clock",
    "rpc": "device.tempoClock",
    "classification": "read",
    "description": "Read the most recent native metronome beat, bar and tick state.",
    "properties": {},
    "required": [],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "get_block_details",
    "rpc": "device.blockDetails",
    "classification": "read",
    "description": "Read live parameters for one occupied Grid block.",
    "properties": {
      "row": "grid-row",
      "column": "grid-column",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "column",
      "expected_preset_name"
    ],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "column",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "list_models",
    "rpc": "device.listModels",
    "classification": "read",
    "description": "Find installed block models and their numeric IDs.",
    "properties": {
      "query": "nullable-string"
    },
    "required": [
      "query"
    ],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "query"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "list_presets",
    "rpc": "device.listPresets",
    "classification": "read",
    "description": "List presets in a setlist, optionally refreshing the device index.",
    "properties": {
      "refresh": "boolean",
      "setlist_key": "nullable-string"
    },
    "required": [
      "refresh",
      "setlist_key"
    ],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {
        "refresh": {
          "type": "boolean"
        },
        "setlist_key": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "refresh",
        "setlist_key"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "list_preset_folders",
    "rpc": "device.listPresetFolders",
    "classification": "read",
    "description": "List preset folders and setlists, optionally refreshing the device index.",
    "properties": {
      "refresh": "boolean"
    },
    "required": [
      "refresh"
    ],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {
        "refresh": {
          "type": "boolean"
        }
      },
      "required": [
        "refresh"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "list_preset_slots",
    "rpc": "device.listPresetSlots",
    "classification": "read",
    "description": "List preset destinations and their occupancy before a persistent write.",
    "properties": {},
    "required": [],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "get_master_volume",
    "rpc": "device.masterVolume",
    "classification": "read",
    "description": "Read the authoritative master output volume.",
    "properties": {},
    "required": [],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "get_device_identity",
    "rpc": "device.identity",
    "classification": "read",
    "description": "Read the connected Quad Cortex serial number, firmware version, type and custom name.",
    "properties": {},
    "required": [],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "get_inhibited_modules",
    "rpc": "device.inhibitedModules",
    "classification": "read",
    "description": "Read the authoritative Global Gate and Global EQ inhibition state.",
    "properties": {},
    "required": [],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "get_preset_screenshot",
    "rpc": "device.presetScreenshot",
    "classification": "read",
    "description": "Read the PNG thumbnail stored for a preset.",
    "properties": {
      "folder_name": "string",
      "position": "integer",
      "is_factory": "boolean"
    },
    "required": [
      "folder_name",
      "position",
      "is_factory"
    ],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {
        "folder_name": {
          "type": "string"
        },
        "position": {
          "type": "integer"
        },
        "is_factory": {
          "type": "boolean"
        }
      },
      "required": [
        "folder_name",
        "position",
        "is_factory"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "capture_screen",
    "rpc": "device.captureScreen",
    "classification": "read",
    "description": "Capture the current Quad Cortex touchscreen as a PNG image.",
    "properties": {},
    "required": [],
    "access": "read-only",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "preview_parameter",
    "rpc": "device.previewParameter",
    "classification": "live-write",
    "description": "Preview a block parameter value without waiting for device verification.",
    "properties": {
      "row": "grid-row",
      "column": "grid-column",
      "parameter_index": "integer",
      "value": "number",
      "expected_value": "number",
      "expected_scene": "scene-index",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "column",
      "parameter_index",
      "value",
      "expected_value",
      "expected_scene",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "parameter_index": {
          "type": "integer"
        },
        "value": {
          "type": "number"
        },
        "expected_value": {
          "type": "number"
        },
        "expected_scene": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "column",
        "parameter_index",
        "value",
        "expected_value",
        "expected_scene",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "create_device_backup",
    "rpc": "device.createBackup",
    "classification": "persistent-write",
    "description": "Create a complete local device backup after explicit confirmation.",
    "properties": {
      "name": "string",
      "confirm_persistent_write": "boolean"
    },
    "required": [
      "name",
      "confirm_persistent_write"
    ],
    "access": "full",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "confirm_persistent_write": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "confirm_persistent_write"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_device_name",
    "rpc": "device.setDeviceName",
    "classification": "persistent-write",
    "description": "Change the Quad Cortex custom name after explicit confirmation.",
    "properties": {
      "name": "string",
      "confirm_persistent_write": "boolean"
    },
    "required": [
      "name",
      "confirm_persistent_write"
    ],
    "access": "full",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "confirm_persistent_write": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "confirm_persistent_write"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "undo_device",
    "rpc": "device.undo",
    "classification": "risky-write",
    "description": "Undo the most recent device edit after explicit confirmation.",
    "properties": {
      "confirm_risky_operation": "boolean"
    },
    "required": [
      "confirm_risky_operation"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "confirm_risky_operation": {
          "type": "boolean"
        }
      },
      "required": [
        "confirm_risky_operation"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "redo_device",
    "rpc": "device.redo",
    "classification": "risky-write",
    "description": "Redo the most recently undone device edit after explicit confirmation.",
    "properties": {
      "confirm_risky_operation": "boolean"
    },
    "required": [
      "confirm_risky_operation"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "confirm_risky_operation": {
          "type": "boolean"
        }
      },
      "required": [
        "confirm_risky_operation"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "tap_screen",
    "rpc": "device.tapScreen",
    "classification": "risky-write",
    "description": "Tap an exact touchscreen pixel after reviewing a fresh screen capture and explicitly confirming the action.",
    "properties": {
      "x": "screen-x",
      "y": "screen-y",
      "confirm_risky_operation": "boolean"
    },
    "required": [
      "x",
      "y",
      "confirm_risky_operation"
    ],
    "access": "full",
    "inputSchema": {
      "type": "object",
      "properties": {
        "x": {
          "type": "integer",
          "minimum": 0,
          "maximum": 799
        },
        "y": {
          "type": "integer",
          "minimum": 0,
          "maximum": 479
        },
        "confirm_risky_operation": {
          "type": "boolean"
        }
      },
      "required": [
        "x",
        "y",
        "confirm_risky_operation"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "select_scene",
    "rpc": "device.selectScene",
    "classification": "live-write",
    "description": "Immediately select a performance scene, numbered 0 through 7.",
    "properties": {
      "scene": "scene-index",
      "expected_preset_name": "string"
    },
    "required": [
      "scene",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "scene": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "scene",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "copy_scene",
    "rpc": "device.copyScene",
    "classification": "live-write",
    "description": "Copy or swap two scenes in the current preset and verify the resulting scene state.",
    "properties": {
      "from_scene": "scene-index",
      "to_scene": "scene-index",
      "swap": "boolean",
      "expected_preset_name": "string"
    },
    "required": [
      "from_scene",
      "to_scene",
      "swap",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "from_scene": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "to_scene": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "swap": {
          "type": "boolean"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "from_scene",
        "to_scene",
        "swap",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_scene_label",
    "rpc": "device.setSceneLabel",
    "classification": "live-write",
    "description": "Set or clear the label of one scene in the current preset.",
    "properties": {
      "scene": "scene-index",
      "label": "nullable-string",
      "expected_preset_name": "string"
    },
    "required": [
      "scene",
      "label",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "scene": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "label": {
          "type": [
            "string",
            "null"
          ]
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "scene",
        "label",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_scene_color",
    "rpc": "device.setSceneColor",
    "classification": "live-write",
    "description": "Set the display color of one scene in the current preset.",
    "properties": {
      "scene": "scene-index",
      "color": "integer",
      "expected_preset_name": "string"
    },
    "required": [
      "scene",
      "color",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "scene": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "color": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "scene",
        "color",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "press_footswitch",
    "rpc": "device.pressFootswitch",
    "classification": "live-write",
    "description": "Press a physical Quad Cortex footswitch by its stable hardware index.",
    "properties": {
      "index": "integer",
      "expected_mode": "string",
      "expected_preset_name": "string"
    },
    "required": [
      "index",
      "expected_mode",
      "expected_preset_name"
    ],
    "access": "performance",
    "inputSchema": {
      "type": "object",
      "properties": {
        "index": {
          "type": "integer"
        },
        "expected_mode": {
          "type": "string"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "index",
        "expected_mode",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "tap_tempo",
    "rpc": "device.tapTempo",
    "classification": "live-write",
    "description": "Tap the dedicated Quad Cortex tempo control through its official MIDI command.",
    "properties": {
      "expected_mode": "string",
      "expected_preset_name": "string"
    },
    "required": [
      "expected_mode",
      "expected_preset_name"
    ],
    "access": "performance",
    "inputSchema": {
      "type": "object",
      "properties": {
        "expected_mode": {
          "type": "string"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "expected_mode",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "navigate_bank",
    "rpc": "device.navigateBank",
    "classification": "live-write",
    "description": "Immediately navigate one performance bank down (-1) or up (1).",
    "properties": {
      "direction": "integer",
      "expected_preset_name": "string",
      "expected_position": "integer"
    },
    "required": [
      "direction",
      "expected_preset_name",
      "expected_position"
    ],
    "access": "performance",
    "inputSchema": {
      "type": "object",
      "properties": {
        "direction": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        },
        "expected_position": {
          "type": "integer"
        }
      },
      "required": [
        "direction",
        "expected_preset_name",
        "expected_position"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "show_tuner",
    "rpc": "device.showTuner",
    "classification": "live-write",
    "description": "Show or hide the tuner.",
    "properties": {
      "shown": "boolean"
    },
    "required": [
      "shown"
    ],
    "access": "performance",
    "inputSchema": {
      "type": "object",
      "properties": {
        "shown": {
          "type": "boolean"
        }
      },
      "required": [
        "shown"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "show_gig_view",
    "rpc": "device.showGigView",
    "classification": "live-write",
    "description": "Show or hide Gig View.",
    "properties": {
      "shown": "boolean"
    },
    "required": [
      "shown"
    ],
    "access": "performance",
    "inputSchema": {
      "type": "object",
      "properties": {
        "shown": {
          "type": "boolean"
        }
      },
      "required": [
        "shown"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "select_mode_slot",
    "rpc": "device.selectModeSlot",
    "classification": "live-write",
    "description": "Select device-configured performance Mode Slot A, B, or C.",
    "properties": {
      "slot": "integer",
      "expected_preset_name": "string"
    },
    "required": [
      "slot",
      "expected_preset_name"
    ],
    "access": "performance",
    "inputSchema": {
      "type": "object",
      "properties": {
        "slot": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "slot",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_master_volume",
    "rpc": "device.setMasterVolume",
    "classification": "risky-write",
    "description": "Set master output volume after explicit user confirmation and stale-value validation.",
    "properties": {
      "value": "integer",
      "expected_value": "integer",
      "confirm_risky_operation": "boolean"
    },
    "required": [
      "value",
      "expected_value",
      "confirm_risky_operation"
    ],
    "access": "performance",
    "inputSchema": {
      "type": "object",
      "properties": {
        "value": {
          "type": "integer"
        },
        "expected_value": {
          "type": "integer"
        },
        "confirm_risky_operation": {
          "type": "boolean"
        }
      },
      "required": [
        "value",
        "expected_value",
        "confirm_risky_operation"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "recall_preset",
    "rpc": "device.recallPreset",
    "classification": "live-write",
    "description": "Immediately recall a preset by setlist key and position.",
    "properties": {
      "setlist_key": "string",
      "position": "integer",
      "expected_preset_name": "string",
      "expected_position": "integer"
    },
    "required": [
      "setlist_key",
      "position",
      "expected_preset_name",
      "expected_position"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "setlist_key": {
          "type": "string"
        },
        "position": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        },
        "expected_position": {
          "type": "integer"
        }
      },
      "required": [
        "setlist_key",
        "position",
        "expected_preset_name",
        "expected_position"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "reload_preset",
    "rpc": "device.reloadPreset",
    "classification": "risky-write",
    "description": "Discard unsaved edits and reload the active preset after explicit host confirmation.",
    "properties": {
      "expected_preset_name": "string",
      "expected_position": "integer",
      "confirm_risky_operation": "boolean"
    },
    "required": [
      "expected_preset_name",
      "expected_position",
      "confirm_risky_operation"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "expected_preset_name": {
          "type": "string"
        },
        "expected_position": {
          "type": "integer"
        },
        "confirm_risky_operation": {
          "type": "boolean"
        }
      },
      "required": [
        "expected_preset_name",
        "expected_position",
        "confirm_risky_operation"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_tempo",
    "rpc": "device.setTempo",
    "classification": "live-write",
    "description": "Immediately set performance tempo from 40 through 240 BPM.",
    "properties": {
      "bpm": "tempo",
      "expected_tempo": "tempo",
      "expected_preset_name": "string"
    },
    "required": [
      "bpm",
      "expected_tempo",
      "expected_preset_name"
    ],
    "access": "performance",
    "inputSchema": {
      "type": "object",
      "properties": {
        "bpm": {
          "type": "integer",
          "minimum": 40,
          "maximum": 240
        },
        "expected_tempo": {
          "type": "integer",
          "minimum": 40,
          "maximum": 240
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "bpm",
        "expected_tempo",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_bypass",
    "rpc": "device.toggleBypass",
    "classification": "live-write",
    "description": "Immediately enable or bypass one Grid block and verify device readback.",
    "properties": {
      "row": "grid-row",
      "column": "grid-column",
      "desired_bypassed": "boolean",
      "expected_bypassed": "boolean",
      "expected_scene": "scene-index",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "column",
      "desired_bypassed",
      "expected_bypassed",
      "expected_scene",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "desired_bypassed": {
          "type": "boolean"
        },
        "expected_bypassed": {
          "type": "boolean"
        },
        "expected_scene": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "column",
        "desired_bypassed",
        "expected_bypassed",
        "expected_scene",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_parameter",
    "rpc": "device.setParameter",
    "classification": "live-write",
    "description": "Immediately set a writable block parameter to an exact display-unit value; QC Control converts and verifies it.",
    "properties": {
      "row": "grid-row",
      "column": "grid-column",
      "parameter_index": "integer",
      "value": "number",
      "expected_value": "number",
      "expected_scene": "scene-index",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "column",
      "parameter_index",
      "value",
      "expected_value",
      "expected_scene",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "parameter_index": {
          "type": "integer"
        },
        "value": {
          "type": "number"
        },
        "expected_value": {
          "type": "number"
        },
        "expected_scene": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "column",
        "parameter_index",
        "value",
        "expected_value",
        "expected_scene",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "move_block",
    "rpc": "device.moveBlock",
    "classification": "live-write",
    "description": "Move an existing Grid block to an empty column in the same row with model and preset guards.",
    "properties": {
      "row": "grid-row",
      "from_column": "grid-column",
      "to_column": "grid-column",
      "expected_model_id": "integer",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "from_column",
      "to_column",
      "expected_model_id",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "from_column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "to_column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "expected_model_id": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "from_column",
        "to_column",
        "expected_model_id",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "add_block",
    "rpc": "device.addBlock",
    "classification": "live-write",
    "description": "Add an installed model to an empty Grid cell and verify the resulting block.",
    "properties": {
      "row": "grid-row",
      "column": "grid-column",
      "model_id": "integer",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "column",
      "model_id",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "model_id": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "column",
        "model_id",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "remove_block",
    "rpc": "device.removeBlock",
    "classification": "live-write",
    "description": "Remove a Grid block after validating its model and active preset.",
    "properties": {
      "row": "grid-row",
      "column": "grid-column",
      "expected_model_id": "integer",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "column",
      "expected_model_id",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "expected_model_id": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "column",
        "expected_model_id",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_block_footswitch",
    "rpc": "device.setBlockFootswitch",
    "classification": "live-write",
    "description": "Assign or clear a Grid block footswitch with preset, model and assignment guards.",
    "properties": {
      "row": "grid-row",
      "column": "grid-column",
      "footswitch": "nullable-integer",
      "expected_footswitch": "nullable-integer",
      "expected_model_id": "integer",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "column",
      "footswitch",
      "expected_footswitch",
      "expected_model_id",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 7
        },
        "footswitch": {
          "type": [
            "integer",
            "null"
          ]
        },
        "expected_footswitch": {
          "type": [
            "integer",
            "null"
          ]
        },
        "expected_model_id": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "column",
        "footswitch",
        "expected_footswitch",
        "expected_model_id",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_chain_input",
    "rpc": "device.setChainInput",
    "classification": "live-write",
    "description": "Change a signal-row input after validating the current route and preset.",
    "properties": {
      "row": "grid-row",
      "input_id": "integer",
      "expected_input_id": "integer",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "input_id",
      "expected_input_id",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "input_id": {
          "type": "integer"
        },
        "expected_input_id": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "input_id",
        "expected_input_id",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_chain_output",
    "rpc": "device.setChainOutput",
    "classification": "live-write",
    "description": "Change a signal-row output after validating the current route and preset.",
    "properties": {
      "row": "grid-row",
      "output_id": "integer",
      "expected_output_id": "integer",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "output_id",
      "expected_output_id",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "output_id": {
          "type": "integer"
        },
        "expected_output_id": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "output_id",
        "expected_output_id",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "set_chain_split",
    "rpc": "device.setChainSplit",
    "classification": "live-write",
    "description": "Set or clear a signal-row split and rejoin with complete stale-route guards.",
    "properties": {
      "row": "grid-row",
      "split_column": "nullable-integer",
      "mix_column": "nullable-integer",
      "expected_split_column": "nullable-integer",
      "expected_mix_column": "nullable-integer",
      "expected_preset_name": "string"
    },
    "required": [
      "row",
      "split_column",
      "mix_column",
      "expected_split_column",
      "expected_mix_column",
      "expected_preset_name"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3
        },
        "split_column": {
          "type": [
            "integer",
            "null"
          ]
        },
        "mix_column": {
          "type": [
            "integer",
            "null"
          ]
        },
        "expected_split_column": {
          "type": [
            "integer",
            "null"
          ]
        },
        "expected_mix_column": {
          "type": [
            "integer",
            "null"
          ]
        },
        "expected_preset_name": {
          "type": "string"
        }
      },
      "required": [
        "row",
        "split_column",
        "mix_column",
        "expected_split_column",
        "expected_mix_column",
        "expected_preset_name"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "save_preset_as",
    "rpc": "device.savePresetAs",
    "classification": "persistent-write",
    "description": "Save the current preset to a reviewed device slot with explicit overwrite confirmation.",
    "properties": {
      "setlist_key": "string",
      "position": "integer",
      "name": "string",
      "expected_preset_name": "string",
      "expected_position": "integer",
      "confirm_overwrite": "boolean",
      "confirm_persistent_write": "boolean"
    },
    "required": [
      "setlist_key",
      "position",
      "name",
      "expected_preset_name",
      "expected_position",
      "confirm_overwrite",
      "confirm_persistent_write"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "setlist_key": {
          "type": "string"
        },
        "position": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "expected_preset_name": {
          "type": "string"
        },
        "expected_position": {
          "type": "integer"
        },
        "confirm_overwrite": {
          "type": "boolean"
        },
        "confirm_persistent_write": {
          "type": "boolean"
        }
      },
      "required": [
        "setlist_key",
        "position",
        "name",
        "expected_preset_name",
        "expected_position",
        "confirm_overwrite",
        "confirm_persistent_write"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "rename_current_preset",
    "rpc": "device.renameCurrentPreset",
    "classification": "persistent-write",
    "description": "Rename the active stored preset after explicit confirmation.",
    "properties": {
      "new_name": "string",
      "expected_preset_name": "string",
      "expected_position": "integer",
      "confirm_persistent_write": "boolean"
    },
    "required": [
      "new_name",
      "expected_preset_name",
      "expected_position",
      "confirm_persistent_write"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "new_name": {
          "type": "string"
        },
        "expected_preset_name": {
          "type": "string"
        },
        "expected_position": {
          "type": "integer"
        },
        "confirm_persistent_write": {
          "type": "boolean"
        }
      },
      "required": [
        "new_name",
        "expected_preset_name",
        "expected_position",
        "confirm_persistent_write"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "copy_preset",
    "rpc": "device.copyPreset",
    "classification": "persistent-write",
    "description": "Copy a device preset to a reviewed destination with explicit overwrite confirmation.",
    "properties": {
      "source_setlist_key": "string",
      "source_position": "integer",
      "source_name": "string",
      "destination_setlist_key": "string",
      "destination_position": "integer",
      "expected_preset_name": "string",
      "expected_position": "integer",
      "confirm_overwrite": "boolean",
      "confirm_persistent_write": "boolean"
    },
    "required": [
      "source_setlist_key",
      "source_position",
      "source_name",
      "destination_setlist_key",
      "destination_position",
      "expected_preset_name",
      "expected_position",
      "confirm_overwrite",
      "confirm_persistent_write"
    ],
    "access": "modify",
    "inputSchema": {
      "type": "object",
      "properties": {
        "source_setlist_key": {
          "type": "string"
        },
        "source_position": {
          "type": "integer"
        },
        "source_name": {
          "type": "string"
        },
        "destination_setlist_key": {
          "type": "string"
        },
        "destination_position": {
          "type": "integer"
        },
        "expected_preset_name": {
          "type": "string"
        },
        "expected_position": {
          "type": "integer"
        },
        "confirm_overwrite": {
          "type": "boolean"
        },
        "confirm_persistent_write": {
          "type": "boolean"
        }
      },
      "required": [
        "source_setlist_key",
        "source_position",
        "source_name",
        "destination_setlist_key",
        "destination_position",
        "expected_preset_name",
        "expected_position",
        "confirm_overwrite",
        "confirm_persistent_write"
      ],
      "additionalProperties": false
    }
  }
] as const;
export type SharedQcActionName = typeof SHARED_QC_ACTIONS[number]["name"];
