// Generated by scripts/generate-gateway-bindings.mjs. Do not edit by hand.
package com.qccontrol.mobile;

final class GeneratedGatewayMethods {
    private GeneratedGatewayMethods() {}

    static final String[] ALL = {
        "system.status",
        "device.reconnect",
        "device.resetSession",
        "device.disconnect",
        "device.snapshot",
        "device.stateEvents",
        "device.tempoClock",
        "device.listModels",
        "device.identity",
        "device.setDeviceName",
        "device.undo",
        "device.redo",
        "device.inhibitedModules",
        "device.presetScreenshot",
        "device.captureScreen",
        "device.tapScreen",
        "device.selectScene",
        "device.toggleBypass",
        "device.moveBlock",
        "device.addBlock",
        "device.removeBlock",
        "device.setBlockFootswitch",
        "device.setChainInput",
        "device.setChainOutput",
        "device.setChainSplit",
        "device.listPresets",
        "device.listPresetFolders",
        "device.navigateBank",
        "device.recallPreset",
        "device.reloadPreset",
        "device.blockDetails",
        "device.previewParameter",
        "device.setParameter",
        "device.setTempo",
        "device.setMasterVolume",
        "device.masterVolume",
        "device.pressFootswitch",
        "device.selectModeSlot",
        "device.listPresetSlots",
        "device.savePresetAs",
        "device.copyPreset",
        "device.renameCurrentPreset",
        "device.createBackup",
        "device.showTuner",
        "device.showGigView"
    };

    static boolean contains(String method) {
        for (String candidate : ALL) if (candidate.equals(method)) return true;
        return false;
    }

    static String dispatchKind(String method) {
        switch (method) {
            case "system.status": return "SYSTEM";
            case "device.reconnect": return "RECONNECT";
            case "device.resetSession": return "RECONNECT";
            case "device.disconnect": return "DISCONNECT";
            case "device.snapshot": return "SNAPSHOT";
            case "device.stateEvents": return "STATE_EVENTS";
            case "device.tempoClock": return "TEMPO_CLOCK";
            case "device.listModels": return "MODELS";
            case "device.identity": return "CORRELATED_READ";
            case "device.setDeviceName": return "SET_DEVICE_NAME";
            case "device.undo": return "PLANNED_WRITE";
            case "device.redo": return "PLANNED_WRITE";
            case "device.inhibitedModules": return "CORRELATED_READ";
            case "device.presetScreenshot": return "CORRELATED_READ";
            case "device.captureScreen": return "CORRELATED_READ";
            case "device.tapScreen": return "TAP_SCREEN";
            case "device.selectScene": return "PLANNED_WRITE";
            case "device.toggleBypass": return "PLANNED_WRITE";
            case "device.moveBlock": return "PLANNED_WRITE";
            case "device.addBlock": return "PLANNED_WRITE";
            case "device.removeBlock": return "PLANNED_WRITE";
            case "device.setBlockFootswitch": return "PLANNED_WRITE";
            case "device.setChainInput": return "PLANNED_WRITE";
            case "device.setChainOutput": return "PLANNED_WRITE";
            case "device.setChainSplit": return "PLANNED_WRITE";
            case "device.listPresets": return "PRESET_LIBRARY";
            case "device.listPresetFolders": return "PRESET_LIBRARY";
            case "device.navigateBank": return "PRESET_WRITE";
            case "device.recallPreset": return "PRESET_WRITE";
            case "device.reloadPreset": return "PRESET_WRITE";
            case "device.blockDetails": return "BLOCK_DETAILS";
            case "device.previewParameter": return "PREVIEW_PARAMETER";
            case "device.setParameter": return "PLANNED_WRITE";
            case "device.setTempo": return "PLANNED_WRITE";
            case "device.setMasterVolume": return "PLANNED_WRITE";
            case "device.masterVolume": return "MASTER_VOLUME";
            case "device.pressFootswitch": return "PLANNED_WRITE";
            case "device.selectModeSlot": return "PLANNED_WRITE";
            case "device.listPresetSlots": return "PRESET_LIBRARY";
            case "device.savePresetAs": return "PERSISTENT_WRITE";
            case "device.copyPreset": return "PERSISTENT_WRITE";
            case "device.renameCurrentPreset": return "PERSISTENT_WRITE";
            case "device.createBackup": return "BACKUP";
            case "device.showTuner": return "PLANNED_WRITE";
            case "device.showGigView": return "PLANNED_WRITE";
            default: return "UNSUPPORTED";
        }
    }
}
