// Generated by scripts/generate-qc-actions.mjs. Do not edit by hand.
package com.qccontrol.mobile;

final class GeneratedRemoteActions {
    private GeneratedRemoteActions() {}

    private static final String[] ALLOWED = {
        "system.status",
        "device.reconnect",
        "device.resetSession",
        "device.disconnect",
        "device.snapshot",
        "device.stateEvents",
        "device.tempoClock",
        "device.blockDetails",
        "device.laneControlDetails",
        "device.listModels",
        "device.listPresets",
        "device.listPresetFolders",
        "device.listPresetSlots",
        "device.masterVolume",
        "device.identity",
        "device.inhibitedModules",
        "device.tunerSettings",
        "device.presetScreenshot",
        "device.captureScreen",
        "device.previewParameter",
        "device.previewLaneControlParameter",
        "device.createBackup",
        "device.setDeviceName",
        "device.undo",
        "device.redo",
        "device.tapScreen",
        "device.selectScene",
        "device.copyScene",
        "device.setSceneLabel",
        "device.setSceneColor",
        "device.pressFootswitch",
        "device.tapTempo",
        "device.navigateBank",
        "device.showTuner",
        "device.showGigView",
        "device.selectModeSlot",
        "device.setMasterVolume",
        "device.recallPreset",
        "device.reloadPreset",
        "device.setTempo",
        "device.toggleBypass",
        "device.setParameter",
        "device.setParameterSceneMode",
        "device.setParameterExpression",
        "device.setLaneControlParameter",
        "device.setLaneControlSceneMode",
        "device.setExpressionBypass",
        "device.moveBlock",
        "device.addBlock",
        "device.removeBlock",
        "device.setBlockFootswitch",
        "device.setStompMomentary",
        "device.setStompLabel",
        "device.setMidiOut",
        "device.setPresetLoadMidiOut",
        "device.setChainInput",
        "device.setChainOutput",
        "device.setChainSplit",
        "device.savePresetAs",
        "device.renameCurrentPreset",
        "device.copyPreset"
    };

    private static final String[] READ_ONLY = {
        "system.status",
        "device.snapshot",
        "device.stateEvents",
        "device.tempoClock",
        "device.blockDetails",
        "device.laneControlDetails",
        "device.listModels",
        "device.listPresets",
        "device.listPresetFolders",
        "device.listPresetSlots",
        "device.masterVolume",
        "device.identity",
        "device.inhibitedModules",
        "device.tunerSettings",
        "device.presetScreenshot",
        "device.captureScreen"
    };

    private static final String[] PERFORMANCE = {
        "device.pressFootswitch",
        "device.tapTempo",
        "device.navigateBank",
        "device.showTuner",
        "device.showGigView",
        "device.selectModeSlot",
        "device.setMasterVolume",
        "device.setTempo"
    };

    private static final String[] MODIFY = {
        "device.previewParameter",
        "device.previewLaneControlParameter",
        "device.undo",
        "device.redo",
        "device.selectScene",
        "device.copyScene",
        "device.setSceneLabel",
        "device.setSceneColor",
        "device.recallPreset",
        "device.reloadPreset",
        "device.toggleBypass",
        "device.setParameter",
        "device.setParameterSceneMode",
        "device.setParameterExpression",
        "device.setLaneControlParameter",
        "device.setLaneControlSceneMode",
        "device.setExpressionBypass",
        "device.moveBlock",
        "device.addBlock",
        "device.removeBlock",
        "device.setBlockFootswitch",
        "device.setStompMomentary",
        "device.setStompLabel",
        "device.setMidiOut",
        "device.setPresetLoadMidiOut",
        "device.setChainInput",
        "device.setChainOutput",
        "device.setChainSplit",
        "device.savePresetAs",
        "device.renameCurrentPreset",
        "device.copyPreset"
    };

    private static final String[] REQUIRES_CONFIRMATION = {
        "device.reconnect",
        "device.resetSession",
        "device.disconnect",
        "device.createBackup",
        "device.setDeviceName",
        "device.undo",
        "device.redo",
        "device.tapScreen",
        "device.setMasterVolume",
        "device.reloadPreset",
        "device.savePresetAs",
        "device.renameCurrentPreset",
        "device.copyPreset"
    };

    static boolean contains(String method) { return contains(ALLOWED, method); }
    static boolean isReadOnly(String method) { return contains(READ_ONLY, method); }
    static boolean isPerformance(String method) { return contains(PERFORMANCE, method); }
    static boolean isModify(String method) { return contains(MODIFY, method); }
    static boolean requiresConfirmation(String method) { return contains(REQUIRES_CONFIRMATION, method); }

    private static boolean contains(String[] values, String method) {
        for (String candidate : values) if (candidate.equals(method)) return true;
        return false;
    }
}
