// Generated by scripts/generate-qc-usb-profile.mjs. Do not edit by hand.
package com.qccontrol.mobile;

final class QcUsbProfile {
    static final int VENDOR_ID = 5418;
    static final int PRODUCT_ID = 34826;
    static final String CORTEX_CONTROL_VERSION = "4.0.1";
    static final int MAX_FRAME_BYTES = 1048576;
    static final int MAX_INFLATED_BYTES = 16777216;
    static final long KEEPALIVE_INTERVAL_MS = 5000L;
    static final long RECONNECT_INTERVAL_MS = 750L;
    static final long PERFORMANCE_MIDI_GAP_MS = 80L;
    static final long HANDSHAKE_TIMEOUT_MS = 30000L;
    static final long HANDSHAKE_ATTEMPT_TIMEOUT_MS = 5000L;
    static final long INITIAL_SYNC_TIMEOUT_MS = 2000L;
    static final long PRESET_SYNC_TIMEOUT_MS = 15000L;
    static final long COMMAND_CONFIRMATION_TIMEOUT_MS = 3000L;
    static final long CONFIRMATION_POLL_INTERVAL_MS = 100L;
    static final int FOOTSWITCH_BASE_CONTROLLER = 35;
    static final int TAP_TEMPO_CONTROLLER = 44;
    static final int MODE_SLOT_CONTROLLER = 47;
    static final int MIDI_PRESSED_VALUE = 127;
    static final int[] LIVE_SUBSCRIPTIONS = {15, 2, 13, 14, 17, 33, 34, 21, 3, 9, 24, 38, 20, 42, 35, 58, 50, 54, 19, 57, 60};

    private QcUsbProfile() {}
}
