// Generated by scripts/generate-qc-payloads.mjs. Do not edit by hand.
use serde::Serialize;

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GridBlock {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_id: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category_id: Option<u32>,
    pub name: String,
    pub kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugin: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugin_id: Option<String>,
    pub row: u32,
    pub column: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bypassed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub glyph: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footswitch: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footswitch_order: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GridRoute {
    pub row: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_id: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_id: Option<u32>,
    pub input: String,
    pub output: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub split_column: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mix_column: Option<i32>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct IoPortState {
    pub kind: String,
    pub id: i32,
    pub label: String,
    pub plugged: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModeSlot {
    pub slot: u32,
    pub label: String,
    pub mode: String,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BypassUpdate {
    pub row: u32,
    pub column: u32,
    pub bypassed: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct QcStateUpdate {
    pub kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_scene: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dirty: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub master_volume: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub index: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub setlist_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_factory: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preset_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tempo: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tempo_led_enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scenes: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scene_colors: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub blocks: Option<Vec<GridBlock>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<GridRoute>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub io_ports: Option<Vec<IoPortState>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode_slots: Option<Vec<ModeSlot>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footswitch_modes: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub row: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub column: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bypassed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bypass_updates: Option<Vec<BypassUpdate>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameter_index: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub normalized_value: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub catalog_refresh: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub observed_at: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ScalePoint {
    pub normalized: f64,
    pub real: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BlockParameter {
    pub index: u32,
    pub display_position: u32,
    pub name: String,
    pub normalized_value: Option<f64>,
    pub display_value: String,
    pub units: String,
    pub r#type: String,
    pub minimum: f64,
    pub maximum: f64,
    pub value_scale: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scale_exponent: Option<f64>,
    pub scale_points: Vec<ScalePoint>,
    pub scale_known: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_precision: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub minimum_label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub midpoint_label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maximum_label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub steps: Option<u32>,
    pub scene_mode: bool,
    pub options: Vec<String>,
    pub writable: bool,
    pub enabled: bool,
    pub expression_assignable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub linked_scene_mode: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression_minimum: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression_maximum: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub led_value: Option<f32>,
    pub wire_value_kind: String,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BlockDetails {
    pub row: u32,
    pub column: u32,
    pub model_id: u32,
    pub name: String,
    pub category: String,
    pub scene: u32,
    pub parameters: Vec<BlockParameter>,
}

