// Generated by scripts/generate-qc-usb-profile.mjs. Do not edit by hand.
pub const VENDOR_ID: u16 = 5418;
pub const PRODUCT_ID: u16 = 34826;
pub const CORTEX_CONTROL_VERSION: &str = "4.0.1";
pub const MAX_FRAME_BYTES: usize = 1048576;
pub const MAX_INFLATED_BYTES: usize = 16777216;
pub const KEEPALIVE_INTERVAL_MS: u64 = 5000;
pub const RECONNECT_INTERVAL_MS: u64 = 750;
pub const PERFORMANCE_MIDI_GAP_MS: u64 = 80;
pub const HANDSHAKE_TIMEOUT_MS: u64 = 30000;
pub const HANDSHAKE_ATTEMPT_TIMEOUT_MS: u64 = 5000;
pub const INITIAL_SYNC_TIMEOUT_MS: u64 = 2000;
pub const PRESET_SYNC_TIMEOUT_MS: u64 = 15000;
pub const COMMAND_CONFIRMATION_TIMEOUT_MS: u64 = 3000;
pub const FOOTSWITCH_BASE_CONTROLLER: u8 = 35;
pub const TAP_TEMPO_CONTROLLER: u8 = 44;
pub const MODE_SLOT_CONTROLLER: u8 = 47;
pub const MIDI_PRESSED_VALUE: u8 = 127;
pub const LIVE_SUBSCRIPTIONS: &[u16] = &[
    3, 9, 24, 38, 20, 42, 35, 58, 50, 54, 19, 15, 57, 60, 17, 33, 34, 21, 2, 13, 14,
];
