# Generated by scripts/generate-qc-payloads.mjs. Do not edit by hand.
from __future__ import annotations
from typing import Any, Literal, NotRequired, TypedDict


class TunerSettings(TypedDict):
    inputPortId: int
    referenceOffsetHz: float
    referenceHz: float
    muted: bool

class BypassExpression(TypedDict):
    pedal: int
    minimum: float
    maximum: float
    mode: int
    invert: bool
    delayMs: int
    latchEmulation: bool

class GridBlock(TypedDict):
    id: str
    modelId: NotRequired[int]
    categoryId: NotRequired[int]
    name: str
    kind: Literal["input", "utility", "capture", "amp", "cab", "mod", "delay", "reverb", "output"]
    category: NotRequired[str]
    plugin: NotRequired[bool]
    pluginId: NotRequired[str]
    row: int
    column: int
    bypassed: NotRequired[bool]
    bypassExpression: NotRequired[BypassExpression]
    color: NotRequired[str]
    glyph: NotRequired[str]
    footswitch: NotRequired[int]
    footswitchOrder: NotRequired[int]

class FootswitchState(TypedDict):
    index: int
    active: bool
    assigned: bool
    color: str
    momentary: NotRequired[bool]
    label: NotRequired[str]

class MidiOutMessage(TypedDict):
    type: int
    channel: int
    param1: int
    param2: int
    param3: int

class MidiOutSource(TypedDict):
    source: int
    messages: list[MidiOutMessage]

class GridRoute(TypedDict):
    row: int
    inputId: NotRequired[int]
    outputId: NotRequired[int]
    input: str
    output: str
    splitColumn: NotRequired[int]
    mixColumn: NotRequired[int]

class IoPortState(TypedDict):
    kind: Literal["input", "output", "headphones", "usb", "expression"]
    id: int
    label: str
    plugged: bool

class ModeSlot(TypedDict):
    slot: Literal[0, 1, 2]
    label: str
    mode: Literal["PRESET", "SCENE", "STOMP", "HYBRID"]

class BypassUpdate(TypedDict):
    row: int
    column: int
    bypassed: bool

class QcStateUpdate(TypedDict):
    kind: Literal["scene", "dirty", "master", "sceneLabel", "sceneColor", "position", "preset", "bypass", "bypassBatch", "mode", "tempo", "parameter", "ioPorts"]
    activeScene: NotRequired[int]
    dirty: NotRequired[bool]
    masterVolume: NotRequired[float]
    index: NotRequired[int]
    label: NotRequired[str]
    color: NotRequired[str]
    setlistKey: NotRequired[str]
    position: NotRequired[int]
    isFactory: NotRequired[bool]
    presetName: NotRequired[str]
    tempo: NotRequired[int]
    tempoLedEnabled: NotRequired[bool]
    scenes: NotRequired[list[str]]
    sceneColors: NotRequired[list[str]]
    footswitchStates: NotRequired[list[FootswitchState]]
    midiOut: NotRequired[list[MidiOutSource]]
    presetLoadMidiOut: NotRequired[list[MidiOutMessage]]
    blocks: NotRequired[list[GridBlock]]
    routes: NotRequired[list[GridRoute]]
    ioPorts: NotRequired[list[IoPortState]]
    mode: NotRequired[Literal["PRESET", "SCENE", "STOMP", "HYBRID"]]
    modeSlots: NotRequired[list[ModeSlot]]
    footswitchModes: NotRequired[list[Literal["PRESET", "SCENE", "STOMP"]]]
    row: NotRequired[int]
    column: NotRequired[int]
    bypassed: NotRequired[bool]
    bypassUpdates: NotRequired[list[BypassUpdate]]
    parameterIndex: NotRequired[int]
    normalizedValue: NotRequired[float]
    catalogRefresh: NotRequired[bool]
    observedAt: NotRequired[int]

class ScalePoint(TypedDict):
    normalized: float
    real: float

class BlockParameter(TypedDict):
    index: int
    displayPosition: int
    name: str
    normalizedValue: float | None
    displayValue: str
    units: str
    type: str
    minimum: float
    maximum: float
    valueScale: str
    scaleExponent: NotRequired[float | None]
    scalePoints: list[ScalePoint]
    scaleKnown: bool
    displayPrecision: NotRequired[int | None]
    minimumLabel: NotRequired[str | None]
    midpointLabel: NotRequired[str | None]
    maximumLabel: NotRequired[str | None]
    steps: NotRequired[int | None]
    sceneMode: bool
    options: list[str]
    writable: bool
    enabled: bool
    expressionAssignable: bool
    linkedSceneMode: NotRequired[int | None]
    expression: NotRequired[int | None]
    expressionMinimum: NotRequired[float | None]
    expressionMaximum: NotRequired[float | None]
    ledValue: NotRequired[float | None]
    wireValueKind: str

class BlockDetails(TypedDict):
    row: int
    column: int
    modelId: int
    name: str
    category: str
    scene: int
    bypassExpression: NotRequired[BypassExpression]
    parameters: list[BlockParameter]

class PresetSnapshot(TypedDict):
    deviceName: str
    presetName: str
    presetLocation: str
    presetPosition: int
    setlistKey: str
    setlistName: str
    mode: Literal["PRESET", "SCENE", "STOMP", "HYBRID"]
    modeSlots: NotRequired[list[ModeSlot]]
    footswitchModes: NotRequired[list[Literal["PRESET", "SCENE", "STOMP"]]]
    activeScene: int
    scenes: list[str]
    sceneColors: NotRequired[list[str]]
    footswitchStates: NotRequired[list[FootswitchState]]
    midiOut: NotRequired[list[MidiOutSource]]
    presetLoadMidiOut: NotRequired[list[MidiOutMessage]]
    blocks: list[GridBlock]
    routes: list[GridRoute]
    ioPorts: NotRequired[list[IoPortState]]
    tempo: int
    tempoLedEnabled: NotRequired[bool]
    tempoPulseEpochMs: NotRequired[int]
    masterVolume: float
    dirty: bool

class DeviceActionResult(TypedDict):
    detail: str
    snapshot: NotRequired[PresetSnapshot]
