# Generated by scripts/generate-gateway-bindings.mjs. Do not edit by hand.
GATEWAY_API_VERSION = 11
GATEWAY_CAPABILITIES = "modelRepoParameterMetadata", "nativeStateEvents", "nativeDeviceIdentity", "nativeRemoteScreen", "nativeSceneManagement", "nativeParameterAssignments", "nativeStompMetadata", "nativePresetMidiOut", "nativeExpressionBypass", "nativeTunerSettings", "nativeLaneControls", "nativeGeneralSettings", "nativeIoSettings",
GATEWAY_METHODS = frozenset(("system.status", "device.reconnect", "device.resetSession", "device.disconnect", "device.snapshot", "device.stateEvents", "device.tempoClock", "device.listModels", "device.identity", "device.setDeviceName", "device.undo", "device.redo", "device.inhibitedModules", "device.tunerSettings", "device.generalSettings", "device.ioSettings", "device.setInputPort", "device.setOutputPort", "device.setUsbPort", "device.setMidiThru", "device.setOutputPairing", "device.setGeneralInteger", "device.setGeneralToggle", "device.setSceneBypassBehavior", "device.setMasterVolumeAssignment", "device.setGlobalBypass", "device.presetScreenshot", "device.captureScreen", "device.tapScreen", "device.selectScene", "device.copyScene", "device.setSceneLabel", "device.setSceneColor", "device.toggleBypass", "device.moveBlock", "device.addBlock", "device.removeBlock", "device.setBlockFootswitch", "device.setStompMomentary", "device.setStompLabel", "device.setMidiOut", "device.setPresetLoadMidiOut", "device.setExpressionBypass", "device.setChainInput", "device.setChainOutput", "device.setChainSplit", "device.listPresets", "device.listPresetFolders", "device.navigateBank", "device.recallPreset", "device.reloadPreset", "device.blockDetails", "device.laneControlDetails", "device.previewParameter", "device.previewLaneControlParameter", "device.setParameter", "device.setLaneControlParameter", "device.setLaneControlSceneMode", "device.setParameterSceneMode", "device.setParameterExpression", "device.setTempo", "device.setMasterVolume", "device.masterVolume", "device.pressFootswitch", "device.tapTempo", "device.selectModeSlot", "device.listPresetSlots", "device.savePresetAs", "device.copyPreset", "device.renameCurrentPreset", "device.createBackup", "device.showTuner", "device.showGigView"))

def dispatch_device_method(device, method, params):
    if method == "device.reconnect":
        return device.reconnect()
    elif method == "device.resetSession":
        return device.reset_session()
    elif method == "device.disconnect":
        return device.disconnect()
    elif method == "device.snapshot":
        return device.snapshot()
    elif method == "device.stateEvents":
        return device.state_events(params.get("afterSequence", 0), params.get("limit", 256))
    elif method == "device.tempoClock":
        return device.tempo_clock_state()
    elif method == "device.listModels":
        return device.list_models()
    elif method == "device.identity":
        return device.identity()
    elif method == "device.setDeviceName":
        return device.set_device_name(params.get("name"))
    elif method == "device.undo":
        return device.undo()
    elif method == "device.redo":
        return device.redo()
    elif method == "device.inhibitedModules":
        return device.inhibited_modules()
    elif method == "device.tunerSettings":
        return device.tuner_settings()
    elif method == "device.generalSettings":
        return device.general_settings()
    elif method == "device.ioSettings":
        return device.io_settings()
    elif method == "device.setInputPort":
        return device.set_input_port(params.get("inputPortId"), params.get("levelDb"), params.get("impedance"), params.get("inputType"), params.get("groundLift"))
    elif method == "device.setOutputPort":
        return device.set_output_port(params.get("outputPortId"), params.get("level"), params.get("groundLift"), params.get("mute"))
    elif method == "device.setUsbPort":
        return device.set_usb_port(params.get("level"), params.get("headphonesSource"), params.get("dryWet"))
    elif method == "device.setMidiThru":
        return device.set_midi_thru(params.get("enabled"))
    elif method == "device.setOutputPairing":
        return device.set_output_pairing(params.get("xlr12Linked"), params.get("out34Linked"))
    elif method == "device.setGeneralInteger":
        return device.set_general_integer(params.get("setting"), params.get("value"))
    elif method == "device.setGeneralToggle":
        return device.set_general_toggle(params.get("setting"), params.get("enabled"))
    elif method == "device.setSceneBypassBehavior":
        return device.set_scene_bypass_behavior(params.get("behavior"))
    elif method == "device.setMasterVolumeAssignment":
        return device.set_master_volume_assignment(params.get("out12"), params.get("out34"), params.get("send12"), params.get("headphones"))
    elif method == "device.setGlobalBypass":
        return device.set_global_bypass(params.get("cab"), params.get("ir"))
    elif method == "device.presetScreenshot":
        return device.preset_screenshot(params.get("folderName"), params.get("position"), params.get("isFactory", False))
    elif method == "device.captureScreen":
        return device.capture_screen()
    elif method == "device.tapScreen":
        return device.tap_screen(params.get("x"), params.get("y"))
    elif method == "device.selectScene":
        return device.select_scene(params.get("scene"), params.get("expectedPresetName", ""))
    elif method == "device.copyScene":
        return device.copy_scene(params.get("fromScene"), params.get("toScene"), params.get("swap", False), params.get("expectedPresetName", ""))
    elif method == "device.setSceneLabel":
        return device.set_scene_label(params.get("scene"), params.get("label"), params.get("expectedPresetName", ""))
    elif method == "device.setSceneColor":
        return device.set_scene_color(params.get("scene"), params.get("color"), params.get("expectedPresetName", ""))
    elif method == "device.toggleBypass":
        return device.toggle_bypass(params.get("row"), params.get("column"), params.get("expectedScene"), params.get("expectedBypassed"), params.get("desiredBypassed"), params.get("expectedPresetName", ""))
    elif method == "device.moveBlock":
        return device.move_block(params.get("row"), params.get("fromColumn"), params.get("toColumn"), params.get("expectedModelId"), params.get("expectedPresetName", ""))
    elif method == "device.addBlock":
        return device.add_block(params.get("row"), params.get("column"), params.get("modelId"), params.get("expectedPresetName", ""))
    elif method == "device.removeBlock":
        return device.remove_block(params.get("row"), params.get("column"), params.get("expectedModelId"), params.get("expectedPresetName", ""))
    elif method == "device.setBlockFootswitch":
        return device.set_block_footswitch(params.get("row"), params.get("column"), params.get("footswitch"), params.get("expectedFootswitch"), params.get("expectedModelId"), params.get("expectedPresetName", ""))
    elif method == "device.setStompMomentary":
        return device.set_stomp_momentary(params.get("footswitch"), params.get("momentary"), params.get("expectedPresetName", ""))
    elif method == "device.setStompLabel":
        return device.set_stomp_label(params.get("footswitch"), params.get("label"), params.get("expectedPresetName", ""))
    elif method == "device.setMidiOut":
        return device.set_midi_out(params.get("source"), params.get("messages"), params.get("expectedPresetName", ""))
    elif method == "device.setPresetLoadMidiOut":
        return device.set_preset_load_midi_out(params.get("messages"), params.get("expectedPresetName", ""))
    elif method == "device.setExpressionBypass":
        return device.set_expression_bypass(params.get("row"), params.get("column"), params.get("pedal"), params.get("mode"), params.get("invert"), params.get("delayMs"), params.get("latchEmulation"), params.get("expectedPresetName", ""))
    elif method == "device.setChainInput":
        return device.set_chain_input(params.get("row"), params.get("inputId"), params.get("expectedInputId"), params.get("expectedPresetName", ""))
    elif method == "device.setChainOutput":
        return device.set_chain_output(params.get("row"), params.get("outputId"), params.get("expectedOutputId"), params.get("expectedPresetName", ""))
    elif method == "device.setChainSplit":
        return device.set_chain_split(params.get("row"), params.get("splitColumn"), params.get("mixColumn"), params.get("expectedSplitColumn"), params.get("expectedMixColumn"), params.get("expectedPresetName", ""))
    elif method == "device.listPresets":
        return device.list_presets(params.get("refresh", False), params.get("setlistKey"))
    elif method == "device.listPresetFolders":
        return device.list_preset_folders(params.get("refresh", False))
    elif method == "device.navigateBank":
        return device.navigate_bank(params.get("direction"), params.get("expectedPresetName", ""), params.get("expectedPosition"))
    elif method == "device.recallPreset":
        return device.recall_preset(params.get("setlistKey"), params.get("position"), params.get("expectedPresetName", ""), params.get("expectedPosition"))
    elif method == "device.reloadPreset":
        return device.reload_preset(params.get("expectedPresetName", ""), params.get("expectedPosition"))
    elif method == "device.blockDetails":
        return device.block_details(params.get("row"), params.get("column"), params.get("expectedPresetName", ""))
    elif method == "device.laneControlDetails":
        return device.lane_control_details(params.get("row"), params.get("control"), params.get("expectedPresetName", ""))
    elif method == "device.previewParameter":
        return device.preview_parameter(params.get("row"), params.get("column"), params.get("parameterIndex"), params.get("value"), params.get("expectedScene"), params.get("expectedPresetName", ""))
    elif method == "device.previewLaneControlParameter":
        return device.preview_lane_control_parameter(params.get("row"), params.get("control"), params.get("parameterIndex"), params.get("value"), params.get("expectedPresetName", ""))
    elif method == "device.setParameter":
        return device.set_parameter(params.get("row"), params.get("column"), params.get("parameterIndex"), params.get("value"), params.get("expectedValue"), params.get("expectedScene"), params.get("expectedPresetName", ""))
    elif method == "device.setLaneControlParameter":
        return device.set_lane_control_parameter(params.get("row"), params.get("control"), params.get("parameterIndex"), params.get("value"), params.get("expectedValue"), params.get("expectedPresetName", ""))
    elif method == "device.setLaneControlSceneMode":
        return device.set_lane_control_scene_mode(params.get("row"), params.get("control"), params.get("parameterIndex"), params.get("enabled"), params.get("expectedPresetName", ""))
    elif method == "device.setParameterSceneMode":
        return device.set_parameter_scene_mode(params.get("row"), params.get("column"), params.get("parameterIndex"), params.get("enabled"), params.get("expectedPresetName", ""))
    elif method == "device.setParameterExpression":
        return device.set_parameter_expression(params.get("row"), params.get("column"), params.get("parameterIndex"), params.get("pedal"), params.get("minimum"), params.get("maximum"), params.get("expectedPresetName", ""))
    elif method == "device.setTempo":
        return device.set_tempo(params.get("bpm"), params.get("expectedTempo"), params.get("expectedPresetName", ""))
    elif method == "device.setMasterVolume":
        return device.set_master_volume(params.get("value"), params.get("expectedValue"))
    elif method == "device.masterVolume":
        return device.master_volume_state()
    elif method == "device.pressFootswitch":
        return device.press_footswitch(params.get("index"), params.get("expectedMode"), params.get("expectedPresetName", ""))
    elif method == "device.tapTempo":
        return device.tap_tempo(params.get("expectedMode"), params.get("expectedPresetName", ""))
    elif method == "device.selectModeSlot":
        return device.select_mode_slot(params.get("slot"), params.get("expectedPresetName", ""))
    elif method == "device.listPresetSlots":
        return device.list_preset_slots()
    elif method == "device.savePresetAs":
        return device.save_preset_as(params.get("setlistKey"), params.get("position"), params.get("name"), params.get("expectedPresetName", ""), params.get("expectedPosition"), params.get("confirmOverwrite", False))
    elif method == "device.copyPreset":
        return device.copy_preset(params.get("sourceSetlistKey"), params.get("sourcePosition"), params.get("sourceName", ""), params.get("destinationSetlistKey"), params.get("destinationPosition"), params.get("expectedPresetName", ""), params.get("expectedPosition"), params.get("confirmOverwrite", False))
    elif method == "device.renameCurrentPreset":
        return device.rename_current_preset(params.get("name"), params.get("expectedPresetName", ""), params.get("expectedPosition"), params.get("confirmRename", False))
    elif method == "device.createBackup":
        return device.create_device_backup(params.get("name", ""))
    elif method == "device.showTuner":
        return device.show_tuner(params.get("shown", True))
    elif method == "device.showGigView":
        return device.show_gig_view(params.get("shown", True))
    raise KeyError(method)
