// Generated by scripts/generate-qc-actions.mjs. Do not edit by hand.
const ALLOWED: &[&str] = &[
    "system.status",
    "device.reconnect",
    "device.resetSession",
    "device.disconnect",
    "device.snapshot",
    "device.stateEvents",
    "device.tempoClock",
    "device.blockDetails",
    "device.listModels",
    "device.listPresets",
    "device.listPresetFolders",
    "device.listPresetSlots",
    "device.masterVolume",
    "device.identity",
    "device.inhibitedModules",
    "device.presetScreenshot",
    "device.captureScreen",
    "device.previewParameter",
    "device.createBackup",
    "device.setDeviceName",
    "device.undo",
    "device.redo",
    "device.tapScreen",
    "device.selectScene",
    "device.pressFootswitch",
    "device.navigateBank",
    "device.showTuner",
    "device.showGigView",
    "device.selectModeSlot",
    "device.setMasterVolume",
    "device.recallPreset",
    "device.reloadPreset",
    "device.setTempo",
    "device.toggleBypass",
    "device.setParameter",
    "device.moveBlock",
    "device.addBlock",
    "device.removeBlock",
    "device.setBlockFootswitch",
    "device.setChainInput",
    "device.setChainOutput",
    "device.setChainSplit",
    "device.savePresetAs",
    "device.renameCurrentPreset",
    "device.copyPreset",
];

const READ_ONLY: &[&str] = &[
    "system.status",
    "device.snapshot",
    "device.stateEvents",
    "device.tempoClock",
    "device.blockDetails",
    "device.listModels",
    "device.listPresets",
    "device.listPresetFolders",
    "device.listPresetSlots",
    "device.masterVolume",
    "device.identity",
    "device.inhibitedModules",
    "device.presetScreenshot",
    "device.captureScreen",
];

const PERFORMANCE: &[&str] = &[
    "device.pressFootswitch",
    "device.navigateBank",
    "device.showTuner",
    "device.showGigView",
    "device.selectModeSlot",
    "device.setMasterVolume",
    "device.setTempo",
];

const MODIFY: &[&str] = &[
    "device.previewParameter",
    "device.undo",
    "device.redo",
    "device.selectScene",
    "device.recallPreset",
    "device.reloadPreset",
    "device.toggleBypass",
    "device.setParameter",
    "device.moveBlock",
    "device.addBlock",
    "device.removeBlock",
    "device.setBlockFootswitch",
    "device.setChainInput",
    "device.setChainOutput",
    "device.setChainSplit",
    "device.savePresetAs",
    "device.renameCurrentPreset",
    "device.copyPreset",
];

pub(crate) fn contains(method: &str) -> bool {
    ALLOWED.contains(&method)
}
pub(crate) fn is_read_only(method: &str) -> bool {
    READ_ONLY.contains(&method)
}
pub(crate) fn is_performance(method: &str) -> bool {
    PERFORMANCE.contains(&method)
}
pub(crate) fn is_modify(method: &str) -> bool {
    MODIFY.contains(&method)
}
