// Generated by scripts/generate-gateway-bindings.mjs. Do not edit by hand.
pub const API_VERSION: u64 = 14;
pub const CAPABILITIES: &[&str] = &[
    "modelRepoParameterMetadata",
    "nativeBroker",
    "nativeStateEvents",
    "nativeDeviceIdentity",
    "nativeRemoteScreen",
    "nativeSceneManagement",
    "nativeParameterAssignments",
    "nativeStompMetadata",
    "nativePresetMidiOut",
    "nativeExpressionBypass",
    "nativeTunerSettings",
    "nativeLaneControls",
    "nativeGeneralSettings",
    "nativeIoSettings",
    "nativeGlobalEq",
    "nativeModeCycle",
    "nativeLooper",
    "nativeLibraryManagement",
];

#[allow(dead_code)]
pub mod rpc {
    pub const RUNTIME_STATUS: &str = "system.status";
    pub const RECONNECT: &str = "device.reconnect";
    pub const RESET_SESSION: &str = "device.resetSession";
    pub const DISCONNECT: &str = "device.disconnect";
    pub const CURRENT_SNAPSHOT: &str = "device.snapshot";
    pub const CURRENT_STATE_EVENTS: &str = "device.stateEvents";
    pub const CURRENT_TEMPO_CLOCK: &str = "device.tempoClock";
    pub const LIST_MODELS: &str = "device.listModels";
    pub const IDENTITY: &str = "device.identity";
    pub const SET_DEVICE_NAME: &str = "device.setDeviceName";
    pub const UNDO: &str = "device.undo";
    pub const REDO: &str = "device.redo";
    pub const INHIBITED_MODULES: &str = "device.inhibitedModules";
    pub const TUNER_SETTINGS: &str = "device.tunerSettings";
    pub const GENERAL_SETTINGS: &str = "device.generalSettings";
    pub const IO_SETTINGS: &str = "device.ioSettings";
    pub const SET_INPUT_PORT: &str = "device.setInputPort";
    pub const SET_OUTPUT_PORT: &str = "device.setOutputPort";
    pub const SET_USB_PORT: &str = "device.setUsbPort";
    pub const SET_MIDI_THRU: &str = "device.setMidiThru";
    pub const SET_OUTPUT_PAIRING: &str = "device.setOutputPairing";
    pub const GLOBAL_EQ: &str = "device.globalEq";
    pub const SET_GLOBAL_EQ_BYPASSED: &str = "device.setGlobalEqBypassed";
    pub const SET_GLOBAL_EQ_BAND: &str = "device.setGlobalEqBand";
    pub const SET_GLOBAL_EQ_OUTPUT: &str = "device.setGlobalEqOutput";
    pub const MODE_CYCLE: &str = "device.modeCycle";
    pub const SET_MODE_CYCLE: &str = "device.setModeCycle";
    pub const LOOPER_STATUS: &str = "device.looperStatus";
    pub const CONTROL_LOOPER: &str = "device.controlLooper";
    pub const RECENTS: &str = "device.recents";
    pub const FAVORITES: &str = "device.favorites";
    pub const SET_FAVORITE: &str = "device.setFavorite";
    pub const PINNED_MODELS: &str = "device.pinnedModels";
    pub const SET_MODEL_PINNED: &str = "device.setModelPinned";
    pub const CAPTURES: &str = "device.captures";
    pub const LOAD_CAPTURE: &str = "device.loadCapture";
    pub const IRS: &str = "device.irs";
    pub const LOAD_IR: &str = "device.loadIr";
    pub const CREATE_SETLIST: &str = "device.createSetlist";
    pub const DELETE_SETLIST: &str = "device.deleteSetlist";
    pub const DUPLICATE_SETLIST: &str = "device.duplicateSetlist";
    pub const DELETE_PRESET: &str = "device.deletePreset";
    pub const MOVE_PRESET: &str = "device.movePreset";
    pub const SET_GENERAL_INTEGER: &str = "device.setGeneralInteger";
    pub const SET_GENERAL_TOGGLE: &str = "device.setGeneralToggle";
    pub const SET_SCENE_BYPASS_BEHAVIOR: &str = "device.setSceneBypassBehavior";
    pub const SET_MASTER_VOLUME_ASSIGNMENT: &str = "device.setMasterVolumeAssignment";
    pub const SET_GLOBAL_BYPASS: &str = "device.setGlobalBypass";
    pub const PRESET_SCREENSHOT: &str = "device.presetScreenshot";
    pub const CAPTURE_SCREEN: &str = "device.captureScreen";
    pub const TAP_SCREEN: &str = "device.tapScreen";
    pub const SELECT_SCENE: &str = "device.selectScene";
    pub const COPY_SCENE: &str = "device.copyScene";
    pub const SET_SCENE_LABEL: &str = "device.setSceneLabel";
    pub const SET_SCENE_COLOR: &str = "device.setSceneColor";
    pub const TOGGLE_BYPASS: &str = "device.toggleBypass";
    pub const MOVE_BLOCK: &str = "device.moveBlock";
    pub const ADD_BLOCK: &str = "device.addBlock";
    pub const REMOVE_BLOCK: &str = "device.removeBlock";
    pub const SET_BLOCK_FOOTSWITCH: &str = "device.setBlockFootswitch";
    pub const SET_STOMP_MOMENTARY: &str = "device.setStompMomentary";
    pub const SET_STOMP_LABEL: &str = "device.setStompLabel";
    pub const SET_MIDI_OUT: &str = "device.setMidiOut";
    pub const SET_PRESET_LOAD_MIDI_OUT: &str = "device.setPresetLoadMidiOut";
    pub const SET_EXPRESSION_BYPASS: &str = "device.setExpressionBypass";
    pub const SET_CHAIN_INPUT: &str = "device.setChainInput";
    pub const SET_CHAIN_OUTPUT: &str = "device.setChainOutput";
    pub const SET_CHAIN_SPLIT: &str = "device.setChainSplit";
    pub const LIST_PRESETS: &str = "device.listPresets";
    pub const LIST_PRESET_FOLDERS: &str = "device.listPresetFolders";
    pub const NAVIGATE_BANK: &str = "device.navigateBank";
    pub const RECALL_PRESET: &str = "device.recallPreset";
    pub const RELOAD_PRESET: &str = "device.reloadPreset";
    pub const BLOCK_DETAILS: &str = "device.blockDetails";
    pub const LANE_CONTROL_DETAILS: &str = "device.laneControlDetails";
    pub const PREVIEW_PARAMETER: &str = "device.previewParameter";
    pub const PREVIEW_LANE_CONTROL_PARAMETER: &str = "device.previewLaneControlParameter";
    pub const SET_PARAMETER: &str = "device.setParameter";
    pub const SET_LANE_CONTROL_PARAMETER: &str = "device.setLaneControlParameter";
    pub const SET_LANE_CONTROL_SCENE_MODE: &str = "device.setLaneControlSceneMode";
    pub const SET_PARAMETER_SCENE_MODE: &str = "device.setParameterSceneMode";
    pub const SET_PARAMETER_EXPRESSION: &str = "device.setParameterExpression";
    pub const SET_TEMPO: &str = "device.setTempo";
    pub const SET_MASTER_VOLUME: &str = "device.setMasterVolume";
    pub const CURRENT_MASTER_VOLUME: &str = "device.masterVolume";
    pub const PRESS_FOOTSWITCH: &str = "device.pressFootswitch";
    pub const TAP_TEMPO: &str = "device.tapTempo";
    pub const SELECT_MODE_SLOT: &str = "device.selectModeSlot";
    pub const LIST_PRESET_SLOTS: &str = "device.listPresetSlots";
    pub const SAVE_PRESET_AS: &str = "device.savePresetAs";
    pub const COPY_PRESET: &str = "device.copyPreset";
    pub const RENAME_CURRENT_PRESET: &str = "device.renameCurrentPreset";
    pub const CREATE_DEVICE_BACKUP: &str = "device.createBackup";
    pub const SHOW_TUNER: &str = "device.showTuner";
    pub const SHOW_GIG_VIEW: &str = "device.showGigView";
}
