// Generated by scripts/generate-gateway-bindings.mjs. Do not edit by hand.
pub const API_VERSION: u64 = 17;
pub const CAPABILITIES: &[&str] = &[
    "modelRepoParameterMetadata",
    "nativeBroker",
    "nativeStateEvents",
    "nativeDeviceIdentity",
    "nativeRemoteScreen",
    "nativeSceneManagement",
    "nativeParameterAssignments",
    "nativeStompMetadata",
    "nativePresetMidiOut",
    "nativeExpressionBypass",
    "nativeTunerSettings",
    "nativeTunerWrites",
    "nativeLaneControls",
    "nativeGeneralSettings",
    "nativeIoSettings",
    "nativeGlobalEq",
    "nativeModeCycle",
    "nativeLooper",
    "nativeLibraryManagement",
    "nativeSplitMute",
    "nativeTempoMetronome",
];
pub const METHODS: &[&str] = &[
    "system.status",
    "device.reconnect",
    "device.resetSession",
    "device.disconnect",
    "device.snapshot",
    "device.stateEvents",
    "device.tempoClock",
    "device.listModels",
    "device.identity",
    "device.setDeviceName",
    "device.undo",
    "device.redo",
    "device.inhibitedModules",
    "device.tunerSettings",
    "device.setTunerInput",
    "device.setTunerMute",
    "device.restoreTunerAudio",
    "device.setTunerReference",
    "device.generalSettings",
    "device.ioSettings",
    "device.setInputPort",
    "device.setOutputPort",
    "device.setUsbPort",
    "device.setMidiThru",
    "device.setOutputPairing",
    "device.globalEq",
    "device.setGlobalEqBypassed",
    "device.setGlobalEqBand",
    "device.setGlobalEqOutput",
    "device.modeCycle",
    "device.setModeCycle",
    "device.globalTempoSettings",
    "device.setTempoMetronome",
    "device.setTempoMode",
    "device.looperStatus",
    "device.controlLooper",
    "device.recents",
    "device.favorites",
    "device.setFavorite",
    "device.pinnedModels",
    "device.setModelPinned",
    "device.captures",
    "device.loadCapture",
    "device.irs",
    "device.loadIr",
    "device.createSetlist",
    "device.deleteSetlist",
    "device.duplicateSetlist",
    "device.deletePreset",
    "device.movePreset",
    "device.setGeneralInteger",
    "device.setGeneralToggle",
    "device.setSceneBypassBehavior",
    "device.setMasterVolumeAssignment",
    "device.setGlobalBypass",
    "device.presetScreenshot",
    "device.captureScreen",
    "device.tapScreen",
    "device.selectScene",
    "device.copyScene",
    "device.setSceneLabel",
    "device.setSceneColor",
    "device.toggleBypass",
    "device.moveBlock",
    "device.addBlock",
    "device.removeBlock",
    "device.setBlockFootswitch",
    "device.setStompMomentary",
    "device.setStompLabel",
    "device.setMidiOut",
    "device.setPresetLoadMidiOut",
    "device.setExpressionBypass",
    "device.setChainInput",
    "device.setChainOutput",
    "device.setChainSplit",
    "device.setSplitMute",
    "device.listPresets",
    "device.listPresetFolders",
    "device.navigateBank",
    "device.recallPreset",
    "device.reloadPreset",
    "device.blockDetails",
    "device.laneControlDetails",
    "device.previewParameter",
    "device.previewLaneControlParameter",
    "device.setParameter",
    "device.setLaneControlParameter",
    "device.setLaneControlSceneMode",
    "device.setParameterSceneMode",
    "device.setParameterExpression",
    "device.setTempo",
    "device.setMasterVolume",
    "device.masterVolume",
    "device.pressFootswitch",
    "device.tapTempo",
    "device.selectModeSlot",
    "device.listPresetSlots",
    "device.savePresetAs",
    "device.copyPreset",
    "device.renameCurrentPreset",
    "device.createBackup",
    "device.showTuner",
    "device.showGigView",
];

#[allow(dead_code)]
pub mod rpc {
    pub const RUNTIME_STATUS: &str = "system.status";
    pub const RECONNECT: &str = "device.reconnect";
    pub const RESET_SESSION: &str = "device.resetSession";
    pub const DISCONNECT: &str = "device.disconnect";
    pub const CURRENT_SNAPSHOT: &str = "device.snapshot";
    pub const CURRENT_STATE_EVENTS: &str = "device.stateEvents";
    pub const CURRENT_TEMPO_CLOCK: &str = "device.tempoClock";
    pub const LIST_MODELS: &str = "device.listModels";
    pub const IDENTITY: &str = "device.identity";
    pub const SET_DEVICE_NAME: &str = "device.setDeviceName";
    pub const UNDO: &str = "device.undo";
    pub const REDO: &str = "device.redo";
    pub const INHIBITED_MODULES: &str = "device.inhibitedModules";
    pub const TUNER_SETTINGS: &str = "device.tunerSettings";
    pub const SET_TUNER_INPUT: &str = "device.setTunerInput";
    pub const SET_TUNER_MUTE: &str = "device.setTunerMute";
    pub const RESTORE_TUNER_AUDIO: &str = "device.restoreTunerAudio";
    pub const SET_TUNER_REFERENCE: &str = "device.setTunerReference";
    pub const GENERAL_SETTINGS: &str = "device.generalSettings";
    pub const IO_SETTINGS: &str = "device.ioSettings";
    pub const SET_INPUT_PORT: &str = "device.setInputPort";
    pub const SET_OUTPUT_PORT: &str = "device.setOutputPort";
    pub const SET_USB_PORT: &str = "device.setUsbPort";
    pub const SET_MIDI_THRU: &str = "device.setMidiThru";
    pub const SET_OUTPUT_PAIRING: &str = "device.setOutputPairing";
    pub const GLOBAL_EQ: &str = "device.globalEq";
    pub const SET_GLOBAL_EQ_BYPASSED: &str = "device.setGlobalEqBypassed";
    pub const SET_GLOBAL_EQ_BAND: &str = "device.setGlobalEqBand";
    pub const SET_GLOBAL_EQ_OUTPUT: &str = "device.setGlobalEqOutput";
    pub const MODE_CYCLE: &str = "device.modeCycle";
    pub const SET_MODE_CYCLE: &str = "device.setModeCycle";
    pub const GLOBAL_TEMPO_SETTINGS: &str = "device.globalTempoSettings";
    pub const SET_TEMPO_METRONOME: &str = "device.setTempoMetronome";
    pub const SET_TEMPO_MODE: &str = "device.setTempoMode";
    pub const LOOPER_STATUS: &str = "device.looperStatus";
    pub const CONTROL_LOOPER: &str = "device.controlLooper";
    pub const RECENTS: &str = "device.recents";
    pub const FAVORITES: &str = "device.favorites";
    pub const SET_FAVORITE: &str = "device.setFavorite";
    pub const PINNED_MODELS: &str = "device.pinnedModels";
    pub const SET_MODEL_PINNED: &str = "device.setModelPinned";
    pub const CAPTURES: &str = "device.captures";
    pub const LOAD_CAPTURE: &str = "device.loadCapture";
    pub const IRS: &str = "device.irs";
    pub const LOAD_IR: &str = "device.loadIr";
    pub const CREATE_SETLIST: &str = "device.createSetlist";
    pub const DELETE_SETLIST: &str = "device.deleteSetlist";
    pub const DUPLICATE_SETLIST: &str = "device.duplicateSetlist";
    pub const DELETE_PRESET: &str = "device.deletePreset";
    pub const MOVE_PRESET: &str = "device.movePreset";
    pub const SET_GENERAL_INTEGER: &str = "device.setGeneralInteger";
    pub const SET_GENERAL_TOGGLE: &str = "device.setGeneralToggle";
    pub const SET_SCENE_BYPASS_BEHAVIOR: &str = "device.setSceneBypassBehavior";
    pub const SET_MASTER_VOLUME_ASSIGNMENT: &str = "device.setMasterVolumeAssignment";
    pub const SET_GLOBAL_BYPASS: &str = "device.setGlobalBypass";
    pub const PRESET_SCREENSHOT: &str = "device.presetScreenshot";
    pub const CAPTURE_SCREEN: &str = "device.captureScreen";
    pub const TAP_SCREEN: &str = "device.tapScreen";
    pub const SELECT_SCENE: &str = "device.selectScene";
    pub const COPY_SCENE: &str = "device.copyScene";
    pub const SET_SCENE_LABEL: &str = "device.setSceneLabel";
    pub const SET_SCENE_COLOR: &str = "device.setSceneColor";
    pub const TOGGLE_BYPASS: &str = "device.toggleBypass";
    pub const MOVE_BLOCK: &str = "device.moveBlock";
    pub const ADD_BLOCK: &str = "device.addBlock";
    pub const REMOVE_BLOCK: &str = "device.removeBlock";
    pub const SET_BLOCK_FOOTSWITCH: &str = "device.setBlockFootswitch";
    pub const SET_STOMP_MOMENTARY: &str = "device.setStompMomentary";
    pub const SET_STOMP_LABEL: &str = "device.setStompLabel";
    pub const SET_MIDI_OUT: &str = "device.setMidiOut";
    pub const SET_PRESET_LOAD_MIDI_OUT: &str = "device.setPresetLoadMidiOut";
    pub const SET_EXPRESSION_BYPASS: &str = "device.setExpressionBypass";
    pub const SET_CHAIN_INPUT: &str = "device.setChainInput";
    pub const SET_CHAIN_OUTPUT: &str = "device.setChainOutput";
    pub const SET_CHAIN_SPLIT: &str = "device.setChainSplit";
    pub const SET_SPLIT_MUTE: &str = "device.setSplitMute";
    pub const LIST_PRESETS: &str = "device.listPresets";
    pub const LIST_PRESET_FOLDERS: &str = "device.listPresetFolders";
    pub const NAVIGATE_BANK: &str = "device.navigateBank";
    pub const RECALL_PRESET: &str = "device.recallPreset";
    pub const RELOAD_PRESET: &str = "device.reloadPreset";
    pub const BLOCK_DETAILS: &str = "device.blockDetails";
    pub const LANE_CONTROL_DETAILS: &str = "device.laneControlDetails";
    pub const PREVIEW_PARAMETER: &str = "device.previewParameter";
    pub const PREVIEW_LANE_CONTROL_PARAMETER: &str = "device.previewLaneControlParameter";
    pub const SET_PARAMETER: &str = "device.setParameter";
    pub const SET_LANE_CONTROL_PARAMETER: &str = "device.setLaneControlParameter";
    pub const SET_LANE_CONTROL_SCENE_MODE: &str = "device.setLaneControlSceneMode";
    pub const SET_PARAMETER_SCENE_MODE: &str = "device.setParameterSceneMode";
    pub const SET_PARAMETER_EXPRESSION: &str = "device.setParameterExpression";
    pub const SET_TEMPO: &str = "device.setTempo";
    pub const SET_MASTER_VOLUME: &str = "device.setMasterVolume";
    pub const CURRENT_MASTER_VOLUME: &str = "device.masterVolume";
    pub const PRESS_FOOTSWITCH: &str = "device.pressFootswitch";
    pub const TAP_TEMPO: &str = "device.tapTempo";
    pub const SELECT_MODE_SLOT: &str = "device.selectModeSlot";
    pub const LIST_PRESET_SLOTS: &str = "device.listPresetSlots";
    pub const SAVE_PRESET_AS: &str = "device.savePresetAs";
    pub const COPY_PRESET: &str = "device.copyPreset";
    pub const RENAME_CURRENT_PRESET: &str = "device.renameCurrentPreset";
    pub const CREATE_DEVICE_BACKUP: &str = "device.createBackup";
    pub const SHOW_TUNER: &str = "device.showTuner";
    pub const SHOW_GIG_VIEW: &str = "device.showGigView";
}
