[package]
name = "qc-voice-control"
version = "0.1.0"
description = "Unofficial modular desktop controller for Quad Cortex"
authors = ["Antoni Ivanov"]
edition = "2021"

[lib]
name = "qc_voice_control_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
